const tableDefaultSortDirections = {
  trifectaStandings: {
    h2hTrifectaPoints: true,
    rotoTrifectaPoints: true,
    trifectaPoints: true,
    playoffPoints: true,
    totalTrifectaPoints: true,
  },
  h2hStandings: {
    wins: true,
    losses: true,
    ties: true,
    winPer: true,
    h2hTrifectaPoints: true,
  },
  rotoStandings: {
    FGPERPoints: true,
    FTPERPoints: true,
    THREEPMPoints: true,
    REBPoints: true,
    ASTPoints: true,
    STLPoints: true,
    BLKPoints: true,
    TOPoints: true,
    PTSPoints: true,
    totalPoints: true,
    rotoTrifectaPoints: true,
  },
  rotoStats: {
    FGPER: true,
    FTPER: true,
    THREEPM: true,
    REB: true,
    AST: true,
    STL: true,
    BLK: true,
    TO: false,
    PTS: true,
  },
  basketballStandings: {
    wins: true,
    losses: true,
    ties: true,
    winPer: true,
    trifectaPoints: true,
    playoffPoints: true,
    totalTrifectaPoints: true,
  },
};

export { tableDefaultSortDirections };
