export const GET_BASKETBALL_ALL_TIME_RECORDS =
  "GET_BASKETBALL_ALL_TIME_RECORDS";
export const GET_BASKETBALL_PAST_CHAMPIONS = "GET_BASKETBALL_PAST_CHAMPIONS";
export const GET_BASKETBALL_BEST_H2H = "GET_BASKETBALL_BEST_H2H";
export const GET_BASKETBALL_BEST_ROTO = "GET_BASKETBALL_BEST_ROTO";
export const SORT_BASKETBALL_HALL_OF_FAME = "SORT_BASKETBALL_HALL_OF_FAME";

export const GET_BASEBALL_ALL_TIME_RECORDS = "GET_BASEBALL_ALL_TIME_RECORDS";
export const GET_BASEBALL_PAST_CHAMPIONS = "GET_BASEBALL_PAST_CHAMPIONS";
export const GET_BASEBALL_BEST_H2H = "GET_BASEBALL_BEST_H2H";
export const GET_BASEBALL_BEST_ROTO = "GET_BASEBALL_BEST_ROTO";
export const SORT_BASEBALL_HALL_OF_FAME = "SORT_BASEBALL_HALL_OF_FAME";

export const GET_FOOTBALL_ALL_TIME_RECORDS = "GET_FOOTBALL_ALL_TIME_RECORDS";
export const GET_FOOTBALL_PAST_CHAMPIONS = "GET_FOOTBALL_PAST_CHAMPIONS";
export const GET_FOOTBALL_BEST_WEEKS = "GET_FOOTBALL_BEST_WEEKS";
export const GET_FOOTBALL_BEST_H2H = "GET_FOOTBALL_BEST_H2H";
export const SORT_FOOTBALL_HALL_OF_FAME = "SORT_FOOTBALL_HALL_OF_FAME";
