export const GET_BASKETBALL_ALL_TIME_RECORDS =
  "GET_BASKETBALL_ALL_TIME_RECORDS";
export const GET_BASKETBALL_PAST_CHAMPIONS = "GET_BASKETBALL_PAST_CHAMPIONS";
export const GET_BASKETBALL_BEST_H2H = "GET_BASKETBALL_BEST_H2H";
export const GET_BASKETBALL_BEST_ROTO = "GET_BASKETBALL_BEST_ROTO";
export const SORT_BASKETBALL_HALL_OF_FAME = "SORT_BASKETBALL_HALL_OF_FAME";
export const GET_BASEBALL_HALL_OF_FAME = "GET_BASEBALL_HALL_OF_FAME";
export const GET_FOOTBALL_HALL_OF_FAME = "GET_FOOTBALL_HALL_OF_FAME";
