export const SCRAPE_YEAR_MATCHUPS_START = "SCRAPE_YEAR_MATCHUPS_START";
export const SCRAPE_YEAR_INDIVIDUAL_MATCHUPS_SUCCESS =
  "SCRAPE_YEAR_INDIVIDUAL_MATCHUPS_SUCCESS";
export const SCRAPE_YEAR_INDIVIDUAL_MATCHUPS_FAILURE =
  "SCRAPE_YEAR_INDIVIDUAL_MATCHUPS_FAILURE";
export const SCRAPE_YEAR_MATCHUPS_FINISH = "SCRAPE_YEAR_MATCHUPS_FINISH";
