export const SCRAPE_DYNASTY_BASEBALL_STANDINGS_START =
  "SCRAPE_DYNASTY_BASEBALL_STANDINGS_START";
export const SCRAPE_DYNASTY_BASEBALL_STANDINGS_SUCCESS =
  "SCRAPE_DYNASTY_BASEBALL_STANDINGS_SUCCESS";
export const SCRAPE_DYNASTY_BASEBALL_STANDINGS_FAILED =
  "SCRAPE_DYNASTY_BASEBALL_STANDINGS_FAILED";

export const SAVE_SCRAPED_DYNASTY_BASEBALL_STANDINGS =
  "SAVE_SCRAPED_DYNASTY_BASEBALL_STANDINGS";
export const SAVE_EXISTING_DYNASTY_BASEBALL_STANDINGS =
  "SAVE_EXISTING_DYNASTY_BASEBALL_STANDINGS";

export const SET_DYNASTY_BASEBALL_STANDINGS_LAST_SCRAPED =
  "SET_DYNASTY_BASEBALL_STANDINGS_LAST_SCRAPED";
export const SORT_DYNASTY_BASEBALL_STANDINGS_TABLE =
  "SORT_DYNASTY_BASEBALL_STANDINGS_TABLE";
