const basketballMatchups2019 = {
  1: [
    {
      ownerNames: "Wesley Chipeco",
      wins: 14,
      losses: 4,
      ties: 0,
      winPer: 0.778,
    },
    {
      ownerNames: "Joshua Liu",
      wins: 15,
      losses: 3,
      ties: 0,
      winPer: 0.861,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 13,
      losses: 4,
      ties: 1,
      winPer: 0.75,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 14,
      losses: 4,
      ties: 0,
      winPer: 0.778,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 14,
      losses: 4,
      ties: 0,
      winPer: 0.778,
    },
    {
      ownerNames: "Tim Fong",
      wins: 13,
      losses: 5,
      ties: 0,
      winPer: 0.722,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 13,
      losses: 5,
      ties: 0,
      winPer: 0.722,
    },
    {
      ownerNames: "Kevin Okamoto, Nick Wang",
      wins: 14,
      losses: 4,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 14,
      losses: 4,
      ties: 0,
      winPer: 0.778,
    },
  ],
  2: [
    {
      ownerNames: "Marcus Lam",
      wins: 4,
      losses: 14,
      ties: 0,
      winPer: 0.222,
    },
    {
      ownerNames: "Joshua Liu",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 6,
      losses: 11,
      ties: 1,
      winPer: 0.361,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 13,
      losses: 5,
      ties: 0,
      winPer: 0.722,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 13,
      losses: 5,
      ties: 0,
      winPer: 0.722,
    },
    {
      ownerNames: "Tim Fong",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 4,
      losses: 14,
      ties: 0,
      winPer: 0.222,
    },
    {
      ownerNames: "Kevin Okamoto, Nick Wang",
      wins: 5,
      losses: 13,
      ties: 0,
      winPer: 0.278,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 13,
      losses: 5,
      ties: 0,
      winPer: 0.722,
    },
  ],
  3: [
    {
      ownerNames: "Marcus Lam",
      wins: 3,
      losses: 15,
      ties: 0,
      winPer: 0.167,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 15,
      losses: 3,
      ties: 0,
      winPer: 0.833,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 14,
      losses: 4,
      ties: 0,
      winPer: 0.778,
    },
    {
      ownerNames: "Tim Fong",
      wins: 13,
      losses: 5,
      ties: 0,
      winPer: 0.722,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 11,
      losses: 7,
      ties: 0,
      winPer: 0.611,
    },
    {
      ownerNames: "Kevin Okamoto, Nick Wang",
      wins: 10,
      losses: 7,
      ties: 1,
      winPer: 0.583,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 15,
      losses: 3,
      ties: 0,
      winPer: 0.833,
    },
  ],
  4: [
    {
      ownerNames: "Marcus Lam",
      wins: 4,
      losses: 13,
      ties: 1,
      winPer: 0.25,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 11,
      losses: 6,
      ties: 1,
      winPer: 0.639,
    },
    {
      ownerNames: "Joshua Liu",
      wins: 3,
      losses: 15,
      ties: 0,
      winPer: 0.2,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 13,
      losses: 4,
      ties: 1,
      winPer: 0.75,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Tim Fong",
      wins: 9,
      losses: 8,
      ties: 1,
      winPer: 0.528,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 9,
      losses: 8,
      ties: 1,
      winPer: 0.528,
    },
    {
      ownerNames: "Kevin Okamoto, Nick Wang",
      wins: 11,
      losses: 7,
      ties: 0,
      winPer: 0.611,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 11,
      losses: 7,
      ties: 0,
      winPer: 0.611,
    },
  ],
  5: [
    {
      ownerNames: "Marcus Lam",
      wins: 4,
      losses: 14,
      ties: 0,
      winPer: 0.222,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 5,
      losses: 13,
      ties: 0,
      winPer: 0.278,
    },
    {
      ownerNames: "Joshua Liu",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 4,
      losses: 13,
      ties: 21,
      winPer: 0.25,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Tim Fong",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Kevin Okamoto, Nick Wang",
      wins: 8,
      losses: 9,
      ties: 1,
      winPer: 0.472,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 13,
      losses: 5,
      ties: 0,
      winPer: 0.722,
    },
  ],
  6: [
    {
      ownerNames: "Marcus Lam",
      wins: 4,
      losses: 14,
      ties: 0,
      winPer: 0.222,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 5,
      losses: 13,
      ties: 0,
      winPer: 0.278,
    },
    {
      ownerNames: "Joshua Liu",
      wins: 4,
      losses: 14,
      ties: 0,
      winPer: 0.222,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
    {
      ownerNames: "Tim Fong",
      wins: 13,
      losses: 4,
      ties: 1,
      winPer: 0.75,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Kevin Okamoto, Nick Wang",
      wins: 3,
      losses: 15,
      ties: 0,
      winPer: 0.167,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 9,
      losses: 7,
      ties: 2,
      winPer: 0.556,
    },
  ],
  7: [
    {
      ownerNames: "Marcus Lam",
      wins: 5,
      losses: 13,
      ties: 0,
      winPer: 0.278,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
    {
      ownerNames: "Joshua Liu",
      wins: 5,
      losses: 13,
      ties: 0,
      winPer: 0.278,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 8,
      losses: 9,
      ties: 1,
      winPer: 0.472,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 4,
      losses: 13,
      ties: 1,
      winPer: 0.25,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 5,
      losses: 13,
      ties: 0,
      winPer: 0.278,
    },
    {
      ownerNames: "Kevin Okamoto, Nick Wang",
      wins: 5,
      losses: 13,
      ties: 0,
      winPer: 0.278,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
  ],
  8: [
    {
      ownerNames: "Marcus Lam",
      wins: 5,
      losses: 13,
      ties: 0,
      winPer: 0.278,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 14,
      losses: 4,
      ties: 0,
      winPer: 0.778,
    },
    {
      ownerNames: "Joshua Liu",
      wins: 7,
      losses: 11,
      ties: 0,
      winPer: 0.389,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 8,
      losses: 9,
      ties: 1,
      winPer: 0.472,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Tim Fong",
      wins: 13,
      losses: 5,
      ties: 0,
      winPer: 0.722,
    },
    {
      ownerNames: "Kevin Okamoto, Nick Wang",
      wins: 7,
      losses: 11,
      ties: 0,
      winPer: 0.278,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
  ],
  9: [
    {
      ownerNames: "Marcus Lam",
      wins: 4,
      losses: 14,
      ties: 0,
      winPer: 0.222,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 13,
      losses: 5,
      ties: 0,
      winPer: 0.722,
    },
    {
      ownerNames: "Joshua Liu",
      wins: 7,
      losses: 10,
      ties: 1,
      winPer: 0.417,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 7,
      losses: 11,
      ties: 0,
      winPer: 0.389,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 9,
      losses: 8,
      ties: 1,
      winPer: 0.528,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 15,
      losses: 3,
      ties: 0,
      winPer: 0.833,
    },
    {
      ownerNames: "Tim Fong",
      wins: 13,
      losses: 5,
      ties: 0,
      winPer: 0.722,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 11,
      losses: 7,
      ties: 0,
      winPer: 0.611,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 16,
      losses: 2,
      ties: 0,
      winPer: 0.889,
    },
  ],
  10: [
    {
      ownerNames: "Marcus Lam",
      wins: 2,
      losses: 16,
      ties: 0,
      winPer: 0.111,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 5,
      losses: 13,
      ties: 0,
      winPer: 0.278,
    },
    {
      ownerNames: "Joshua Liu",
      wins: 3,
      losses: 15,
      ties: 0,
      winPer: 0.167,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 7,
      losses: 11,
      ties: 0,
      winPer: 0.389,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 5,
      losses: 13,
      ties: 0,
      winPer: 0.278,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 7,
      losses: 9,
      ties: 2,
      winPer: 0.444,
    },
    {
      ownerNames: "Tim Fong",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
    {
      ownerNames: "Kevin Okamoto, Nick Wang",
      wins: 2,
      losses: 16,
      ties: 0,
      winPer: 0.111,
    },
  ],
};

export { basketballMatchups2019 };
