const json = [
  {
    date: "2019/05/04",
    owner1: "Marcus Lam",
    owner1PlayersReceived: ["Max Muncy"],
    owner2: "Wesley Chipeco",
    owner2PlayersReceived: ["Yoan Moncada"],
  },
  {
    date: "2019/01/12",
    owner1: "Wesley Chipeco",
    owner1PlayersReceived: ["CJ McCollum", "Will Barton", "Reggie Bullock"],
    owner2: "Joshua Apostol",
    owner2PlayersReceived: ["Myles Turner", "Bobby Portis"],
  },
  {
    date: "2018/11/06",
    owner1: "Bryan Kuh",
    owner1PlayersReceived: ["Amari Cooper"],
    owner2: "Joshua Apostol",
    owner2PlayersReceived: ["Jordan Howard"],
  },
  {
    date: "2018/10/09",
    owner1: "Bryan Kuh",
    owner1PlayersReceived: ["James Conner"],
    owner2: "Joshua Apostol",
    owner2PlayersReceived: ["Amari Cooper", "Royce Freeman"],
  },
  {
    date: "2018/09/13",
    owner1: "Bryan Kuh",
    owner1PlayersReceived: ["Le'Veon Bell"],
    owner2: "Ryan Tomimitsu",
    owner2PlayersReceived: ["Adrian Peterson", "Marquise Goodwin"],
  },
  {
    date: "2018/07/07",
    owner1: "Kevin Okamoto, Joshua Liu",
    owner1PlayersReceived: ["Dee Gordon", "Nolan Arenado", "Dallas Keuchel"],
    owner2: "Tim Fong",
    owner2PlayersReceived: [
      "Brandon Morrow",
      "Mitch Haniger",
      "Charlie Morton",
    ],
  },
  {
    date: "2017/11/28",
    owner1: "Wesley Chipeco",
    owner1PlayersReceived: [
      "Thaddeus Young",
      "#217 Overall (22nd Rd) 2018 Baseball Pick (Alex Claudio)",
    ],
    owner2: "Tim Fong",
    owner2PlayersReceived: ["Reggie Jackson"],
  },
  {
    date: "2017/11/14",
    owner1: "Marcus Lam",
    owner1PlayersReceived: [
      "Mike Conley",
      "Kentavious Caldwell-Pope",
      "Jonas Valanciunas",
    ],
    owner2: "Wesley Chipeco",
    owner2PlayersReceived: ["Reggie Jackson", "Kent Bazemore", "Steven Adams"],
  },
  {
    date: "2017/11/14",
    owner1: "Marcus Lam",
    owner1PlayersReceived: [
      "Otto Porter Jr",
      "#136 Overall (14th Rd) 2018 Baseball Pick (Nomar Mazara)",
    ],
    owner2: "Nick Wang",
    owner2PlayersReceived: ["Al Horford"],
  },
  {
    date: "2017/10/14",
    owner1: "Bryan Kuh",
    owner1PlayersReceived: ["T.Y. Hilton", "Frank Gore"],
    owner2: "Joshua Aguirre",
    owner2PlayersReceived: ["Pierre Garcon", "Tarik Cohen"],
  },
  {
    date: "2017/10/05",
    owner1: "Wesley Chipeco",
    owner1PlayersReceived: [
      "Aaron Rodgers",
      "Rishard Mathews",
      "#95 Overall (10th Rd) 2018 Basketball Pick (Gary Harris)",
    ],
    owner2: "Tim Fong",
    owner2PlayersReceived: ["Kirk Cousins", "Davante Adams", "Tyreek Hill"],
  },
  {
    date: "2017/10/04",
    owner1: "Tim Fong",
    owner1PlayersReceived: ["Brandon Marshall"],
    owner2: "Wayne Fong",
    owner2PlayersReceived: ["Martavis Bryant"],
  },
  {
    date: "2017/10/04",
    owner1: "Tim Fong",
    owner1PlayersReceived: ["C.J. Prosise"],
    owner2: "Wayne Fong",
    owner2PlayersReceived: ["Jeremy Maclin"],
  },
  {
    date: "2017/09/13",
    owner1: "Bryan Kuh",
    owner1PlayersReceived: ["David Johnson"],
    owner2: "Tim Fong",
    owner2PlayersReceived: ["Jeremy Maclin"],
  },
  {
    date: "2017/06/11",
    owner1: "Wesley Chipeco",
    owner1PlayersReceived: ["Andrew Miller"],
    owner2: "Joshua Apostol",
    owner2PlayersReceived: ["AJ Ramos", "Zack Cozart"],
  },
  {
    date: "2017/05/03",
    owner1: "Bryan Kuh",
    owner1PlayersReceived: ["Drew Pomeranz"],
    owner2: "Joshua Apostol",
    owner2PlayersReceived: ["Tony Watson"],
  },
  {
    date: "2017/04/15",
    owner1: "Wesley Chipeco",
    owner1PlayersReceived: ["Adam Eaton", "Robinson Cano"],
    owner2: "Kevin Okamoto, Joshua Liu",
    owner2PlayersReceived: ["Alex Bregman", "Ryan Braun"],
  },
  {
    date: "2017/01/04",
    owner1: "Marcus Lam",
    owner1PlayersReceived: ["C.J. Prosise"],
    owner2: "Wayne Fong",
    owner2PlayersReceived: ["Jeremy Maclin"],
  },
  {
    date: "2016/10/06",
    owner1: "Marcus Lam",
    owner1PlayersReceived: ["Latavis Murray"],
    owner2: "Bryan Kuh",
    owner2PlayersReceived: ["Stefon Diggs"],
  },
  {
    date: "2016/09/30",
    owner1: "Joshua Aguirre",
    owner1PlayersReceived: ["Spencer Ware"],
    owner2: "Joshua Apostol",
    owner2PlayersReceived: ["Will Fuller V"],
  },
  {
    date: "2016/09/22",
    owner1: "Nick Wang",
    owner1PlayersReceived: ["Travis Benjamin"],
    owner2: "Bryan Kuh",
    owner2PlayersReceived: ["Doug Martin"],
  },
  {
    date: "2016/08/05",
    owner1: "Marcus Lam",
    owner1PlayersReceived: ["Clayton Kershaw"],
    owner2: "Ryan Tomimitsu",
    owner2PlayersReceived: ["Masahiro Tanaka"],
  },
  {
    date: "2016/07/30",
    owner1: "Kevin Okamoto, Joshua Liu",
    owner1PlayersReceived: ["Eric Hosmer", "Robinson Cano"],
    owner2: "Joshua Apostol",
    owner2PlayersReceived: ["Jose Abreu", "Miguel Sano"],
  },
  {
    date: "2016/06/25",
    owner1: "Joshua Apostol",
    owner1PlayersReceived: ["Drew Pomeranz"],
    owner2: "Tim Fong",
    owner2PlayersReceived: ["Will Harris"],
  },
  {
    date: "2016/06/21",
    owner1: "Marcus Lam",
    owner1PlayersReceived: ["Kyle Hendricks", "Carlos Carrasco"],
    owner2: "Kevin Okamoto, Joshua Liu",
    owner2PlayersReceived: ["Marcus Stroman", "Zack Greinke"],
  },
  {
    date: "2016/06/17",
    owner1: "Ryan Tomimitsu",
    owner1PlayersReceived: ["Jose Bautista"],
    owner2: "Wayne Fong",
    owner2PlayersReceived: ["Stephen Piscotty", "Jean Segura"],
  },
  {
    date: "2016/06/06",
    owner1: "Kevin Okamoto, Joshua Liu",
    owner1PlayersReceived: ["Jose Abreu"],
    owner2: "Ryan Tomimitsu",
    owner2PlayersReceived: ["Stephen Piscotty"],
  },
  {
    date: "2016/05/28",
    owner1: "Marcus Lam",
    owner1PlayersReceived: ["Zack Greinke", "Sam Dyson", "Matt Duffy"],
    owner2: "Tim Fong",
    owner2PlayersReceived: [
      "Jeff Samardzija",
      "Andrew Miller",
      "Jason Heyward",
    ],
  },
  {
    date: "2016/05/28",
    owner1: "Wesley Chipeco",
    owner1PlayersReceived: ["Brett Gardner"],
    owner2: "Tim Fong",
    owner2PlayersReceived: ["Sonny Gray"],
  },
  {
    date: "2016/05/28",
    owner1: "Wesley Chipeco",
    owner1PlayersReceived: ["Jerad Eickhoff"],
    owner2: "Kevin Okamoto, Joshua Liu",
    owner2PlayersReceived: ["Jake Odorizzi"],
  },
  {
    date: "2016/05/28",
    owner1: "Marcus Lam",
    owner1PlayersReceived: ["Lance McCullers"],
    owner2: "Wesley Chipeco",
    owner2PlayersReceived: ["Vince Velasquez"],
  },
  {
    date: "2016/05/28",
    owner1: "Kevin Okamoto, Joshua Liu",
    owner1PlayersReceived: ["Jacob deGrom"],
    owner2: "Tim Fong",
    owner2PlayersReceived: ["Steven Matz"],
  },
  {
    date: "2016/05/07",
    owner1: "Wesley Chipeco",
    owner1PlayersReceived: ["Corey Dickerson"],
    owner2: "Tim Fong",
    owner2PlayersReceived: ["Brett Gardner"],
  },
  {
    date: "2016/05/05",
    owner1: "Kevin Okamoto, Joshua Liu",
    owner1PlayersReceived: ["Lorenzo Cain"],
    owner2: "Joshua Aguirre",
    owner2PlayersReceived: ["Curtis Granderson"],
  },
  {
    date: "2016/05/02",
    owner1: "Marcus Lam",
    owner1PlayersReceived: ["Marcus Stroman", "Carlos Gomez"],
    owner2: "Ryan Tomimitsu",
    owner2PlayersReceived: ["John Lackey", "Yasiel Puig"],
  },
  {
    date: "2015/11/27",
    owner1: "Bryan Kuh",
    owner1PlayersReceived: ["Amari Cooper"],
    owner2: "Joshua Apostol",
    owner2PlayersReceived: ["Jeremy Hill"],
  },
  {
    date: "2015/10/30",
    owner1: "Marcus Lam",
    owner1PlayersReceived: ["C.J. Anderson", "DeSean Jackson"],
    owner2: "Tim Fong",
    owner2PlayersReceived: ["Stefon Diggs"],
  },
  {
    date: "2015/10/24",
    owner1: "Wesley Chipeco",
    owner1PlayersReceived: ["Marcus Mariota", "Delanie Walker"],
    owner2: "Ryan Tomimitsu",
    owner2PlayersReceived: ["Sammy Watkins"],
  },
  {
    date: "2015/10/23",
    owner1: "Marcus Lam",
    owner1PlayersReceived: ["Phillip Rivers"],
    owner2: "Nick Wang",
    owner2PlayersReceived: ["Carson Palmer"],
  },
  {
    date: "2015/10/21",
    owner1: "Wesley Chipeco",
    owner1PlayersReceived: ["Alshon Jeffery"],
    owner2: "Bryan Kuh",
    owner2PlayersReceived: ["Jeremy Hill"],
  },
];
