const json = {
  totalMatchups: [
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.389,
      baseballWinPer: 0.667,
      footballWinPer: 1,
      totalWinPer: 0.685,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.556,
      baseballWinPer: 0.444,
      footballWinPer: 1,
      totalWinPer: 0.667,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.333,
      baseballWinPer: 0.583,
      footballWinPer: 0.5,
      totalWinPer: 0.472,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.333,
      baseballWinPer: 0.542,
      footballWinPer: 0.5,
      totalWinPer: 0.458,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.25,
      baseballWinPer: 0.438,
      footballWinPer: 0.5,
      totalWinPer: 0.396,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.667,
      baseballWinPer: 0.431,
      footballWinPer: 0,
      totalWinPer: 0.366,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.333,
      baseballWinPer: 0.694,
      footballWinPer: 0,
      totalWinPer: 0.343,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.5,
      baseballWinPer: 0.333,
      footballWinPer: 0,
      totalWinPer: 0.278,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.444,
      baseballWinPer: 0.188,
      footballWinPer: 0,
      totalWinPer: 0.211,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Tim Fong",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Nick Wang",
      wins: 7,
      losses: 11,
      ties: 0,
      winPer: 0.389,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
    {
      ownerNames: "Wyane Fong",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 4,
      losses: 13,
      ties: 1,
      winPer: 0.25,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Wayne Fong",
      wins: 24,
      losses: 10,
      ties: 2,
      winPer: 0.694,
    },
    {
      ownerNames: "Nick Wang",
      wins: 15,
      losses: 7,
      ties: 2,
      winPer: 0.667,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 13,
      losses: 9,
      ties: 2,
      winPer: 0.583,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 12,
      losses: 10,
      ties: 2,
      winPer: 0.542,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 14,
      losses: 18,
      ties: 4,
      winPer: 0.444,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 9,
      losses: 12,
      ties: 3,
      winPer: 0.438,
    },
    {
      ownerNames: "Tim Fong",
      wins: 15,
      losses: 20,
      ties: 1,
      winPer: 0.431,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 12,
      losses: 24,
      ties: 0,
      winPer: 0.333,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 4,
      losses: 19,
      ties: 1,
      winPer: 0.188,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Nick Wang",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 257.8,
      pointsAgainst: 158.5,
      pointsDiff: 99.3,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 104.8,
      pointsAgainst: 68.9,
      pointsDiff: 35.9,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 111.9,
      pointsAgainst: 92,
      pointsDiff: 19.9,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 99.4,
      pointsAgainst: 94,
      pointsDiff: 5.4,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 188.6,
      pointsAgainst: 187.8,
      pointsDiff: 0.8,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 196.7,
      pointsAgainst: 196.2,
      pointsDiff: 0.5,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 184.9,
      pointsAgainst: 190.7,
      pointsDiff: -5.8,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 66.5,
      pointsAgainst: 84.5,
      pointsDiff: -18,
    },
    {
      ownerNames: "Tim Fong",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 85.6,
      pointsAgainst: 113.4,
      pointsDiff: -27.8,
    },
  ],
};
