const json = {
  totalMatchups: [
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.333,
      baseballWinPer: 0.778,
      footballWinPer: 1,
      totalWinPer: 0.704,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.5,
      baseballWinPer: 0.542,
      footballWinPer: 1,
      totalWinPer: 0.681,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.5,
      baseballWinPer: 0.458,
      footballWinPer: 1,
      totalWinPer: 0.653,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.444,
      baseballWinPer: 0.5,
      footballWinPer: 1,
      totalWinPer: 0.648,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.389,
      baseballWinPer: 0.5,
      footballWinPer: 1,
      totalWinPer: 0.63,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.75,
      baseballWinPer: 0.563,
      footballWinPer: 0.5,
      totalWinPer: 0.604,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.722,
      baseballWinPer: 0.625,
      footballWinPer: 0,
      totalWinPer: 0.449,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.389,
      baseballWinPer: 0.667,
      footballWinPer: 0.0,
      totalWinPer: 0.352,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.417,
      baseballWinPer: 0.292,
      footballWinPer: 0,
      totalWinPer: 0.236,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Joshua Aguirre",
      wins: 13,
      losses: 4,
      ties: 1,
      winPer: 0.75,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 13,
      losses: 5,
      ties: 0,
      winPer: 0.72,
    },
    {
      ownerNames: "Tim Fong",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 7,
      losses: 10,
      ties: 1,
      winPer: 0.417,
    },
    {
      ownerNames: "Wyane Fong",
      wins: 7,
      losses: 11,
      ties: 0,
      winPer: 0.389,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 7,
      losses: 11,
      ties: 0,
      winPer: 0.389,
    },
    {
      ownerNames: "Nick Wang",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Nick Wang",
      wins: 27,
      losses: 7,
      ties: 2,
      winPer: 0.778,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 15,
      losses: 7,
      ties: 2,
      winPer: 0.667,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 15,
      losses: 9,
      ties: 0,
      winPer: 0.625,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 12,
      losses: 9,
      ties: 3,
      winPer: 0.563,
    },
    {
      ownerNames: "Tim Fong",
      wins: 12,
      losses: 10,
      ties: 2,
      winPer: 0.542,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 16,
      losses: 16,
      ties: 4,
      winPer: 0.5,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 16,
      losses: 16,
      ties: 4,
      winPer: 0.5,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 15,
      losses: 18,
      ties: 3,
      winPer: 0.458,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 7,
      losses: 17,
      ties: 0,
      winPer: 0.292,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Wesley Chipeco",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 161.2,
      pointsAgainst: 91.5,
      pointsDiff: 69.7,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 209.9,
      pointsAgainst: 161.2,
      pointsDiff: 48.7,
    },
    {
      ownerNames: "Tim Fong",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 126.7,
      pointsAgainst: 100.5,
      pointsDiff: 26.2,
    },
    {
      ownerNames: "Nick Wang",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 104.1,
      pointsAgainst: 79.1,
      pointsDiff: 25,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 99.1,
      pointsAgainst: 94.7,
      pointsDiff: 4.4,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 196.2,
      pointsAgainst: 196.7,
      pointsDiff: -0.5,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 115.9,
      pointsAgainst: 116.3,
      pointsDiff: -0.4,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 190.5,
      pointsAgainst: 204.7,
      pointsDiff: -14.2,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 180.1,
      pointsAgainst: 220.6,
      pointsDiff: -40.5,
    },
  ],
};
