const json = {
  totalMatchups: [
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.611,
      baseballWinPer: 0.514,
      footballWinPer: 1,
      totalWinPer: 0.708,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.472,
      baseballWinPer: 0.521,
      footballWinPer: 1,
      totalWinPer: 0.664,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.556,
      baseballWinPer: 0.104,
      footballWinPer: 1,
      totalWinPer: 0.553,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.667,
      baseballWinPer: 0.375,
      footballWinPer: 0.5,
      totalWinPer: 0.514,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.417,
      baseballWinPer: 0.069,
      footballWinPer: 0.5,
      totalWinPer: 0.329,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.611,
      baseballWinPer: 0.333,
      footballWinPer: 0,
      totalWinPer: 0.315,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.667,
      baseballWinPer: 0.222,
      footballWinPer: 0,
      totalWinPer: 0.296,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.333,
      baseballWinPer: 0.333,
      footballWinPer: 0,
      totalWinPer: 0.222,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.444,
      baseballWinPer: 0.104,
      footballWinPer: 0,
      totalWinPer: 0.183,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Wesley Chipeco",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 11,
      losses: 7,
      ties: 0,
      winPer: 0.611,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 11,
      losses: 7,
      ties: 0,
      winPer: 0.611,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Tim Fong",
      wins: 8,
      losses: 9,
      ties: 1,
      winPer: 0.472,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 7,
      losses: 10,
      ties: 1,
      winPer: 0.417,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Tim Fong",
      wins: 12,
      losses: 11,
      ties: 1,
      winPer: 0.521,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 15,
      losses: 14,
      ties: 7,
      winPer: 0.514,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 12,
      losses: 21,
      ties: 3,
      winPer: 0.375,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 7,
      losses: 15,
      ties: 2,
      winPer: 0.333,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 7,
      losses: 15,
      ties: 2,
      winPer: 0.333,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 7,
      losses: 27,
      ties: 2,
      winPer: 0.222,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 2,
      losses: 21,
      ties: 1,
      winPer: 0.104,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 2,
      losses: 21,
      ties: 1,
      winPer: 0.104,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 2,
      losses: 33,
      ties: 1,
      winPer: 0.069,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Tim Fong",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 265,
      pointsAgainst: 164.4,
      pointsDiff: 100.6,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 110.6,
      pointsAgainst: 67.5,
      pointsDiff: 43.1,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 105.8,
      pointsAgainst: 81.7,
      pointsDiff: 24.1,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 186.3,
      pointsAgainst: 173.6,
      pointsDiff: -12.7,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 156.8,
      pointsAgainst: 212.6,
      pointsDiff: -55.8,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 79.1,
      pointsAgainst: 104.1,
      pointsDiff: -25,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 78.8,
      pointsAgainst: 114.7,
      pointsDiff: -35.9,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 87.5,
      pointsAgainst: 133.1,
      pointsDiff: -45.6,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 158.5,
      pointsAgainst: 257.8,
      pointsDiff: -99.3,
    },
  ],
};
