const json = {
  totalMatchups: [
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.667,
      baseballWinPer: 0.667,
      footballWinPer: 1,
      totalWinPer: 0.778,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.722,
      baseballWinPer: 0.486,
      footballWinPer: 0.5,
      totalWinPer: 0.569,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.667,
      baseballWinPer: 0.347,
      footballWinPer: 0.5,
      totalWinPer: 0.505,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.333,
      baseballWinPer: 0.542,
      footballWinPer: 0.5,
      totalWinPer: 0.458,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.667,
      baseballWinPer: 0.458,
      footballWinPer: 0,
      totalWinPer: 0.375,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.389,
      baseballWinPer: 0.639,
      footballWinPer: 0,
      totalWinPer: 0.343,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.389,
      baseballWinPer: 0.5,
      footballWinPer: 0,
      totalWinPer: 0.296,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.361,
      baseballWinPer: 0.354,
      footballWinPer: 0,
      totalWinPer: 0.238,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.444,
      baseballWinPer: 0.229,
      footballWinPer: 0,
      totalWinPer: 0.225,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Tim Fong",
      wins: 13,
      losses: 5,
      ties: 0,
      winPer: 0.722,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Nick Wang",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 7,
      losses: 11,
      ties: 0,
      winPer: 0.389,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 7,
      losses: 11,
      ties: 0,
      winPer: 0.389,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 6,
      losses: 11,
      ties: 1,
      winPer: 0.361,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Nick Wang",
      wins: 15,
      losses: 7,
      ties: 2,
      winPer: 0.667,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 22,
      losses: 12,
      ties: 2,
      winPer: 0.639,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 11,
      losses: 9,
      ties: 4,
      winPer: 0.542,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 16,
      losses: 16,
      ties: 4,
      winPer: 0.5,
    },
    {
      ownerNames: "Tim Fong",
      wins: 16,
      losses: 17,
      ties: 3,
      winPer: 0.486,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 10,
      losses: 12,
      ties: 2,
      winPer: 0.458,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 8,
      losses: 15,
      ties: 1,
      winPer: 0.354,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 12,
      losses: 23,
      ties: 1,
      winPer: 0.347,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 5,
      losses: 18,
      ties: 1,
      winPer: 0.229,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Nick Wang",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 114.7,
      pointsAgainst: 78.8,
      pointsDiff: 35.9,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 243.5,
      pointsAgainst: 209.2,
      pointsDiff: 34.3,
    },
    {
      ownerNames: "Tim Fong",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 208.6,
      pointsAgainst: 179.7,
      pointsDiff: 28.9,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 215.5,
      pointsAgainst: 226.5,
      pointsDiff: -11,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 94.7,
      pointsAgainst: 99.1,
      pointsDiff: -4.4,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 97,
      pointsAgainst: 99.4,
      pointsDiff: -5.4,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 88.8,
      pointsAgainst: 118.1,
      pointsDiff: -29.3,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 77.1,
      pointsAgainst: 112.1,
      pointsDiff: -35,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 179.9,
      pointsAgainst: 227.2,
      pointsDiff: -47.3,
    },
  ],
};
