const json = {
  totalMatchups: [
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.833,
      baseballWinPer: 0.479,
      footballWinPer: 1,
      totalWinPer: 0.771,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.722,
      baseballWinPer: 0.25,
      footballWinPer: 1,
      totalWinPer: 0.657,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.611,
      baseballWinPer: 0.361,
      footballWinPer: 1,
      totalWinPer: 0.657,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.556,
      baseballWinPer: 0.403,
      footballWinPer: 1,
      totalWinPer: 0.653,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.611,
      baseballWinPer: 0.333,
      footballWinPer: 1,
      totalWinPer: 0.648,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.222,
      baseballWinPer: 0.479,
      footballWinPer: 1,
      totalWinPer: 0.567,
    },
    {
      ownerNames: "Wesley Chiepeco",
      basketballWinPer: 0.361,
      baseballWinPer: 0.188,
      footballWinPer: 0,
      totalWinPer: 0.516,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.667,
      baseballWinPer: 0.306,
      footballWinPer: 0.5,
      totalWinPer: 0.491,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.389,
      baseballWinPer: 0.486,
      footballWinPer: 0,
      totalWinPer: 0.292,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Tim Fong",
      wins: 15,
      losses: 3,
      ties: 0,
      winPer: 0.833,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 13,
      losses: 5,
      ties: 0,
      winPer: 0.722,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 11,
      losses: 7,
      ties: 0,
      winPer: 0.611,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 11,
      losses: 7,
      ties: 0,
      winPer: 0.611,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Nick Wang",
      wins: 7,
      losses: 11,
      ties: 0,
      winPer: 0.389,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 6,
      losses: 11,
      ties: 1,
      winPer: 0.361,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 4,
      losses: 14,
      ties: 0,
      winPer: 0.222,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Nick Wang",
      wins: 14,
      losses: 15,
      ties: 7,
      winPer: 0.486,
    },
    {
      ownerNames: "Tim Fong",
      wins: 11,
      losses: 12,
      ties: 1,
      winPer: 0.479,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 10,
      losses: 11,
      ties: 3,
      winPer: 0.479,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 14,
      losses: 21,
      ties: 1,
      winPer: 0.403,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 12,
      losses: 22,
      ties: 2,
      winPer: 0.361,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 7,
      losses: 15,
      ties: 2,
      winPer: 0.333,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 10,
      losses: 24,
      ties: 2,
      winPer: 0.306,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 6,
      losses: 18,
      ties: 0,
      winPer: 0.25,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 4,
      losses: 19,
      ties: 1,
      winPer: 0.188,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 258.1,
      pointsAgainst: 146.9,
      pointsDiff: 111.2,
    },
    {
      ownerNames: "Tim Fong",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 139.1,
      pointsAgainst: 72.1,
      pointsDiff: 67,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 239.5,
      pointsAgainst: 193.8,
      pointsDiff: 45.7,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 220.6,
      pointsAgainst: 180.1,
      pointsDiff: 40.5,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 137.4,
      pointsAgainst: 101.2,
      pointsDiff: 36.2,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 112.1,
      pointsAgainst: 77.1,
      pointsDiff: 35,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 108.3,
      pointsAgainst: 103.9,
      pointsDiff: 4.4,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 190.7,
      pointsAgainst: 184.9,
      pointsDiff: 5.8,
    },
    {
      ownerNames: "Nick Wang",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 81.7,
      pointsAgainst: 105.8,
      pointsDiff: -24.1,
    },
  ],
};
