const json = {
  totalMatchups: [
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.639,
      baseballWinPer: 0.646,
      footballWinPer: 1,
      totalWinPer: 0.762,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.5,
      baseballWinPer: 0.667,
      footballWinPer: 1,
      totalWinPer: 0.722,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.556,
      baseballWinPer: 0.806,
      footballWinPer: 0.5,
      totalWinPer: 0.62,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.333,
      baseballWinPer: 0.625,
      footballWinPer: 0.5,
      totalWinPer: 0.486,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.639,
      baseballWinPer: 0.813,
      footballWinPer: 0,
      totalWinPer: 0.484,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.556,
      baseballWinPer: 0.813,
      footballWinPer: 0.0,
      totalWinPer: 0.456,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.611,
      baseballWinPer: 0.5,
      footballWinPer: 0.0,
      totalWinPer: 0.37,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.417,
      baseballWinPer: 0.583,
      footballWinPer: 0.0,
      totalWinPer: 0.333,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.5,
      baseballWinPer: 0.458,
      footballWinPer: 0.0,
      totalWinPer: 0.319,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 11,
      losses: 6,
      ties: 1,
      winPer: 0.639,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 11,
      losses: 6,
      ties: 1,
      winPer: 0.639,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 11,
      losses: 7,
      ties: 0,
      winPer: 0.611,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Tim Fong",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 7,
      losses: 10,
      ties: 1,
      winPer: 0.417,
    },
    {
      ownerNames: "Nick Wang",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Wayne Fong",
      wins: 19,
      losses: 4,
      ties: 1,
      winPer: 0.813,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 19,
      losses: 4,
      ties: 1,
      winPer: 0.813,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 28,
      losses: 6,
      ties: 2,
      winPer: 0.806,
    },
    {
      ownerNames: "Tim Fong",
      wins: 16,
      losses: 8,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 15,
      losses: 8,
      ties: 1,
      winPer: 0.646,
    },
    {
      ownerNames: "Nick Wang",
      wins: 21,
      losses: 12,
      ties: 3,
      winPer: 0.625,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 20,
      losses: 14,
      ties: 2,
      winPer: 0.583,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 16,
      losses: 16,
      ties: 4,
      winPer: 0.5,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 11,
      losses: 13,
      ties: 0,
      winPer: 0.458,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 227.2,
      pointsAgainst: 179.9,
      pointsDiff: 47.3,
    },
    {
      ownerNames: "Tim Fong",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 98.6,
      pointsAgainst: 97,
      pointsDiff: 1.6,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 201.5,
      pointsAgainst: 195.3,
      pointsDiff: 6.2,
    },
    {
      ownerNames: "Nick Wang",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 173.6,
      pointsAgainst: 186.3,
      pointsDiff: -12.7,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 92,
      pointsAgainst: 111.9,
      pointsDiff: -19.9,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 78.9,
      pointsAgainst: 112.5,
      pointsDiff: -33.6,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 193.8,
      pointsAgainst: 239.6,
      pointsDiff: -45.8,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 81.6,
      pointsAgainst: 139.9,
      pointsDiff: -58.3,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 91.5,
      pointsAgainst: 161.2,
      pointsDiff: -69.7,
    },
  ],
};
