export const SCRAPE_BASEBALL_STANDINGS_START =
  "SCRAPE_BASEBALL_STANDINGS_START";
export const SCRAPE_BASEBALL_STANDINGS_SUCCESS =
  "SCRAPE_BASEBALL_STANDINGS_SUCCESS";
export const SCRAPE_BASEBALL_STANDINGS_FAILED =
  "SCRAPE_BASEBALL_STANDINGS_FAILED";

export const SET_LAST_SCRAPED = "LAST_SCRAPED";
