export const SCRAPE_H2H_BASEBALL_STANDINGS_START =
  "SCRAPE_H2H_BASEBALL_STANDINGS_START";
export const SCRAPE_H2H_BASEBALL_STANDINGS_SUCCESS =
  "SCRAPE_H2H_BASEBALL_STANDINGS_SUCCESS";
export const SCRAPE_H2H_BASEBALL_STANDINGS_FAILED =
  "SCRAPE_H2H_BASEBALL_STANDINGS_FAILED";

export const ADD_H2H_TRIFECTA_POINTS = "ADD_H2H_TRIFECTA_POINTS";

export const SCRAPE_ROTO_BASEBALL_STANDINGS_START =
  "SCRAPE_ROTO_BASEBALL_STANDINGS_START";
export const SCRAPE_ROTO_BASEBALL_STANDINGS_SUCCESS =
  "SCRAPE_ROTO_BASEBALL_STANDINGS_SUCCESS";
export const SCRAPE_ROTO_BASEBALL_STANDINGS_FAILED =
  "SCRAPE_ROTO_BASEBALL_STANDINGS_FAILED";

export const ADD_ROTO_TRIFECTA_POINTS = "ADD_ROTO_TRIFECTA_POINTS";

export const ADD_TOTAL_TRIFECTA_POINTS = "ADD_TOTAL_TRIFECTA_POINTS";

export const SET_LAST_SCRAPED = "LAST_SCRAPED";

export const SORT_BY_COLUMN = "SORT_BY_COLUMN";
