const json = {
  year: "2016",
  totalMatchups: [
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.5,
      baseballWinPer: 0.563,
      footballWinPer: 1,
      totalWinPer: 0.688,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.5,
      baseballWinPer: 0.514,
      footballWinPer: 1,
      totalWinPer: 0.671,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.306,
      baseballWinPer: 0.292,
      footballWinPer: 1,
      totalWinPer: 0.533,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.778,
      baseballWinPer: 0.528,
      footballWinPer: 0,
      totalWinPer: 0.435,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.5,
      baseballWinPer: 0.75,
      footballWinPer: 0,
      totalWinPer: 0.417,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.833,
      baseballWinPer: 0.417,
      footballWinPer: 0,
      totalWinPer: 0.417,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.556,
      baseballWinPer: 0.583,
      footballWinPer: 0,
      totalWinPer: 0.38,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.444,
      baseballWinPer: 0.521,
      footballWinPer: 0,
      totalWinPer: 0.322,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.444,
      baseballWinPer: 0.514,
      footballWinPer: 0,
      totalWinPer: 0.319,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Wesley Chipeco",
      wins: 15,
      losses: 3,
      ties: 0,
      winPer: 0.833,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 14,
      losses: 4,
      ties: 0,
      winPer: 0.778,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Tim Fong",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Nick Wang",
      wins: 5,
      losses: 12,
      ties: 1,
      winPer: 0.306,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Tim Fong",
      wins: 26,
      losses: 8,
      ties: 2,
      winPer: 0.75,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 14,
      losses: 10,
      ties: 0,
      winPer: 0.583,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 13,
      losses: 10,
      ties: 1,
      winPer: 0.563,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 19,
      losses: 17,
      ties: 0,
      winPer: 0.528,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 11,
      losses: 10,
      ties: 3,
      winPer: 0.521,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 17,
      losses: 16,
      ties: 3,
      winPer: 0.514,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 16,
      losses: 15,
      ties: 5,
      winPer: 0.514,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 9,
      losses: 13,
      ties: 2,
      winPer: 0.417,
    },
    {
      ownerNames: "Nick Wang",
      wins: 5,
      losses: 15,
      ties: 4,
      winPer: 0.292,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Joshua Aguirre",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 180.3,
      pointsAgainst: 131.7,
      pointsDiff: 48.6,
    },
    {
      ownerNames: "Nick Wang",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 175.3,
      pointsAgainst: 129.3,
      pointsDiff: 46,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 119.1,
      pointsAgainst: 105.5,
      pointsDiff: 13.6,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 91,
      pointsAgainst: 104.7,
      pointsDiff: -13.7,
    },
    {
      ownerNames: "Tim Fong",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 94,
      pointsAgainst: 109.3,
      pointsDiff: -15.3,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 71.4,
      pointsAgainst: 93.2,
      pointsDiff: -21.8,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 164,
      pointsAgainst: 189.7,
      pointsDiff: -25.7,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 72.6,
      pointsAgainst: 112.8,
      pointsDiff: -40.2,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 154.5,
      pointsAgainst: 247.4,
      pointsDiff: -92.9,
    },
  ],
};
