const json = {
  year: "2016",
  totalMatchups: [
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.722,
      baseballWinPer: 0.708,
      footballWinPer: 1,
      totalWinPer: 0.81,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.472,
      baseballWinPer: 0.625,
      footballWinPer: 1,
      totalWinPer: 0.699,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.556,
      baseballWinPer: 0.479,
      footballWinPer: 1,
      totalWinPer: 0.678,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.556,
      baseballWinPer: 0.458,
      footballWinPer: 1,
      totalWinPer: 0.671,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.778,
      baseballWinPer: 0.625,
      footballWinPer: 0.5,
      totalWinPer: 0.634,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.583,
      baseballWinPer: 0.667,
      footballWinPer: 0.5,
      totalWinPer: 0.583,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.778,
      baseballWinPer: 0.611,
      footballWinPer: 0,
      totalWinPer: 0.463,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.583,
      baseballWinPer: 0.667,
      footballWinPer: 0,
      totalWinPer: 0.417,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.667,
      baseballWinPer: 0.472,
      footballWinPer: 0,
      totalWinPer: 0.38,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Wayne Fong",
      wins: 14,
      losses: 4,
      ties: 0,
      winPer: 0.778,
    },
    {
      ownerNames: "Tim Fong",
      wins: 14,
      losses: 4,
      ties: 0,
      winPer: 0.778,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 13,
      losses: 5,
      ties: 0,
      winPer: 0.722,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Nick Wang",
      wins: 10,
      losses: 7,
      ties: 1,
      winPer: 0.583,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 10,
      losses: 7,
      ties: 1,
      winPer: 0.583,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 8,
      losses: 9,
      ties: 1,
      winPer: 0.472,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Wesley Chipeco",
      wins: 16,
      losses: 6,
      ties: 2,
      winPer: 0.708,
    },
    {
      ownerNames: "Nick Wang",
      wins: 24,
      losses: 12,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 16,
      losses: 8,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 14,
      losses: 8,
      ties: 2,
      winPer: 0.625,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 14,
      losses: 8,
      ties: 2,
      winPer: 0.625,
    },
    {
      ownerNames: "Tim Fong",
      wins: 21,
      losses: 13,
      ties: 2,
      winPer: 0.611,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 10,
      losses: 11,
      ties: 3,
      winPer: 0.479,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 14,
      losses: 16,
      ties: 6,
      winPer: 0.472,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 15,
      losses: 18,
      ties: 3,
      winPer: 0.458,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Bryan Kuh",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 247.4,
      pointsAgainst: 154.5,
      pointsDiff: 92.9,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 128.2,
      pointsAgainst: 99.3,
      pointsDiff: 28.9,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 97,
      pointsAgainst: 80.2,
      pointsDiff: 16.8,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 110,
      pointsAgainst: 96.7,
      pointsDiff: 13.3,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 221.9,
      pointsAgainst: 202.3,
      pointsDiff: 19.6,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 253.1,
      pointsAgainst: 245.9,
      pointsDiff: 7.2,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 81.6,
      pointsAgainst: 91.7,
      pointsDiff: -10.1,
    },
    {
      ownerNames: "Tim Fong",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 111.6,
      pointsAgainst: 129.4,
      pointsDiff: -17.8,
    },
    {
      ownerNames: "Nick Wang",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 126.6,
      pointsAgainst: 214.8,
      pointsDiff: -88.2,
    },
  ],
};
