const json = {
  year: "2016",
  totalMatchups: [
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.833,
      baseballWinPer: 0.438,
      footballWinPer: 1,
      totalWinPer: 0.757,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.611,
      baseballWinPer: 0.625,
      footballWinPer: 1,
      totalWinPer: 0.745,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.5,
      baseballWinPer: 0.583,
      footballWinPer: 1,
      totalWinPer: 0.694,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.5,
      baseballWinPer: 0.486,
      footballWinPer: 1,
      totalWinPer: 0.662,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.333,
      baseballWinPer: 0.583,
      footballWinPer: 1,
      totalWinPer: 0.639,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.639,
      baseballWinPer: 0.486,
      footballWinPer: 0.5,
      totalWinPer: 0.542,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.417,
      baseballWinPer: 0.333,
      footballWinPer: 0.5,
      totalWinPer: 0.417,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.333,
      baseballWinPer: 0.778,
      footballWinPer: 0,
      totalWinPer: 0.37,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.5,
      baseballWinPer: 0.438,
      footballWinPer: 0,
      totalWinPer: 0.313,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Wesley Chipeco",
      wins: 14,
      losses: 2,
      ties: 2,
      winPer: 0.833,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 11,
      losses: 6,
      ties: 1,
      winPer: 0.639,
    },
    {
      ownerNames: "Nick Wang",
      wins: 11,
      losses: 7,
      ties: 0,
      winPer: 0.611,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 7,
      losses: 10,
      ties: 1,
      winPer: 0.417,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
    {
      ownerNames: "Tim Fong",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Tim Fong",
      wins: 26,
      losses: 6,
      ties: 4,
      winPer: 0.778,
    },
    {
      ownerNames: "Nick Wang",
      wins: 21,
      losses: 12,
      ties: 3,
      winPer: 0.625,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 14,
      losses: 10,
      ties: 0,
      winPer: 0.583,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 13,
      losses: 9,
      ties: 0,
      winPer: 0.583,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 17,
      losses: 18,
      ties: 1,
      winPer: 0.486,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 16,
      losses: 17,
      ties: 3,
      winPer: 0.486,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 10,
      losses: 13,
      ties: 1,
      winPer: 0.438,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 10,
      losses: 13,
      ties: 1,
      winPer: 0.438,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 8,
      losses: 16,
      ties: 0,
      winPer: 0.333,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 109.5,
      pointsAgainst: 86.2,
      pointsDiff: 23.3,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 78.1,
      pointsAgainst: 52.4,
      pointsDiff: 19.4,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 94.1,
      pointsAgainst: 79.5,
      pointsDiff: 14.6,
    },
    {
      ownerNames: "Nick Wang",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 195.8,
      pointsAgainst: 181.5,
      pointsDiff: 14.3,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 90.3,
      pointsAgainst: 90.1,
      pointsDiff: 0.2,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 202.3,
      pointsAgainst: 221.9,
      pointsDiff: -19.6,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 195.9,
      pointsAgainst: 219.2,
      pointsDiff: -23.3,
    },
    {
      ownerNames: "Tim Fong",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 91.5,
      pointsAgainst: 124.1,
      pointsDiff: -32.6,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 131.7,
      pointsAgainst: 180.3,
      pointsDiff: -48.6,
    },
  ],
};
