const json = {
  year: "2016",
  totalMatchups: [
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.556,
      baseballWinPer: 0.729,
      footballWinPer: 1,
      totalWinPer: 0.762,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.556,
      baseballWinPer: 0.486,
      footballWinPer: 1,
      totalWinPer: 0.681,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.444,
      baseballWinPer: 0.563,
      footballWinPer: 1,
      totalWinPer: 0.669,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.389,
      baseballWinPer: 0.458,
      footballWinPer: 1,
      totalWinPer: 0.616,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.667,
      baseballWinPer: 0.5,
      footballWinPer: 0.583,
      totalWinPer: 0.583,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.444,
      baseballWinPer: 0.5,
      footballWinPer: 0.5,
      totalWinPer: 0.481,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.5,
      baseballWinPer: 0.514,
      footballWinPer: 0,
      totalWinPer: 0.338,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.444,
      baseballWinPer: 0.563,
      footballWinPer: 0,
      totalWinPer: 0.336,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.444,
      baseballWinPer: 0.542,
      footballWinPer: 0,
      totalWinPer: 0.329,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Wesley Chipeco",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Tim Fong",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Nick Wang",
      wins: 7,
      losses: 9,
      ties: 2,
      winPer: 0.444,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 7,
      losses: 11,
      ties: 0,
      winPer: 0.389,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Tim Fong",
      wins: 17,
      losses: 6,
      ties: 1,
      winPer: 0.729,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 13,
      losses: 9,
      ties: 2,
      winPer: 0.583,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 12,
      losses: 9,
      ties: 3,
      winPer: 0.563,
    },
    {
      ownerNames: "Nick Wang",
      wins: 12,
      losses: 9,
      ties: 3,
      winPer: 0.563,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 18,
      losses: 15,
      ties: 3,
      winPer: 0.542,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 18,
      losses: 17,
      ties: 1,
      winPer: 0.514,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 16,
      losses: 16,
      ties: 4,
      winPer: 0.5,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 15,
      losses: 16,
      ties: 5,
      winPer: 0.486,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 10,
      losses: 12,
      ties: 2,
      winPer: 0.458,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Bryan Kuh",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 112.8,
      pointsAgainst: 72.6,
      pointsDiff: 40.2,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 195.2,
      pointsAgainst: 168.3,
      pointsDiff: 26.9,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 115.9,
      pointsAgainst: 104.6,
      pointsDiff: 11.3,
    },
    {
      ownerNames: "Tim Fong",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 169.3,
      pointsAgainst: 167.9,
      pointsDiff: 1.4,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 166.1,
      pointsAgainst: 195.7,
      pointsDiff: -29.6,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 153.9,
      pointsAgainst: 191.7,
      pointsDiff: -37.8,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 96.7,
      pointsAgainst: 110,
      pointsDiff: -13.3,
    },
    {
      ownerNames: "Nick Wang",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 92,
      pointsAgainst: 106.3,
      pointsDiff: -14.3,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 86.2,
      pointsAgainst: 109.5,
      pointsDiff: -23.3,
    },
  ],
};
