const json = {
  year: "2016",
  totalMatchups: [
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.722,
      baseballWinPer: 0.708,
      footballWinPer: 1,
      totalWinPer: 0.81,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.333,
      baseballWinPer: 0.528,
      footballWinPer: 1,
      totalWinPer: 0.62,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.583,
      baseballWinPer: 0.653,
      footballWinPer: 0.5,
      totalWinPer: 0.579,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.556,
      baseballWinPer: 0.792,
      footballWinPer: 0,
      totalWinPer: 0.449,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.778,
      baseballWinPer: 0.542,
      footballWinPer: 0,
      totalWinPer: 0.44,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.556,
      baseballWinPer: 0.438,
      footballWinPer: 0,
      totalWinPer: 0.331,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.5,
      baseballWinPer: 0.486,
      footballWinPer: 0,
      totalWinPer: 0.329,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.5,
      baseballWinPer: 0.417,
      footballWinPer: 0,
      totalWinPer: 0.306,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.278,
      baseballWinPer: 0.431,
      footballWinPer: 0,
      totalWinPer: 0.236,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Wayne Fong",
      wins: 14,
      losses: 4,
      ties: 0,
      winPer: 0.778,
    },
    {
      ownerNames: "Nick Wang",
      wins: 13,
      losses: 5,
      ties: 0,
      winPer: 0.722,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 10,
      losses: 7,
      ties: 1,
      winPer: 0.583,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Tim Fong",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 4,
      losses: 12,
      ties: 2,
      winPer: 0.278,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Tim Fong",
      wins: 18,
      losses: 4,
      ties: 2,
      winPer: 0.792,
    },
    {
      ownerNames: "Nick Wang",
      wins: 17,
      losses: 7,
      ties: 0,
      winPer: 0.708,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 22,
      losses: 11,
      ties: 3,
      winPer: 0.653,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 13,
      losses: 11,
      ties: 0,
      winPer: 0.542,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 16,
      losses: 14,
      ties: 6,
      winPer: 0.528,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 16,
      losses: 17,
      ties: 3,
      winPer: 0.486,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 9,
      losses: 12,
      ties: 3,
      winPer: 0.438,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 14,
      losses: 19,
      ties: 3,
      winPer: 0.431,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 10,
      losses: 14,
      ties: 0,
      winPer: 0.417,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Nick Wang",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 118.3,
      pointsAgainst: 88.9,
      pointsDiff: 29.4,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 91.7,
      pointsAgainst: 81.6,
      pointsDiff: 10.1,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 179.2,
      pointsAgainst: 200.5,
      pointsDiff: -21.3,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 90.1,
      pointsAgainst: 90.3,
      pointsDiff: -0.2,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 105.5,
      pointsAgainst: 119.1,
      pointsDiff: -13.6,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 168.3,
      pointsAgainst: 195.2,
      pointsDiff: -26.7,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 84.3,
      pointsAgainst: 114.4,
      pointsDiff: -30.1,
    },
    {
      ownerNames: "Tim Fong",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 194.9,
      pointsAgainst: 231.6,
      pointsDiff: -36.7,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 149.5,
      pointsAgainst: 202.3,
      pointsDiff: -52.8,
    },
  ],
};
