const json = {
  year: "2016",
  totalMatchups: [
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.75,
      baseballWinPer: 0.514,
      footballWinPer: 1,
      totalWinPer: 0.755,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.556,
      baseballWinPer: 0.438,
      footballWinPer: 1,
      totalWinPer: 0.665,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.444,
      baseballWinPer: 0.403,
      footballWinPer: 1,
      totalWinPer: 0.616,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.417,
      baseballWinPer: 0.333,
      footballWinPer: 1,
      totalWinPer: 0.583,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.722,
      baseballWinPer: 0.708,
      footballWinPer: 0,
      totalWinPer: 0.477,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.694,
      baseballWinPer: 0.708,
      footballWinPer: 0,
      totalWinPer: 0.467,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.417,
      baseballWinPer: 0.458,
      footballWinPer: 0.5,
      totalWinPer: 0.458,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.389,
      baseballWinPer: 0.375,
      footballWinPer: 0,
      totalWinPer: 0.255,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.278,
      baseballWinPer: 0.292,
      footballWinPer: 0,
      totalWinPer: 0.19,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Wesley Chipeco",
      wins: 13,
      losses: 4,
      ties: 1,
      winPer: 0.75,
    },
    {
      ownerNames: "Tim Fong",
      wins: 13,
      losses: 5,
      ties: 0,
      winPer: 0.722,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 12,
      losses: 5,
      ties: 1,
      winPer: 0.694,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 9,
      losses: 7,
      ties: 2,
      winPer: 0.556,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 7,
      losses: 10,
      ties: 1,
      winPer: 0.417,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 7,
      losses: 10,
      ties: 1,
      winPer: 0.417,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 7,
      losses: 11,
      ties: 0,
      winPer: 0.389,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 5,
      losses: 13,
      ties: 0,
      winPer: 0.278,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Bryan Kuh",
      wins: 15,
      losses: 5,
      ties: 4,
      winPer: 0.78,
    },
    {
      ownerNames: "Tim Fong",
      wins: 17,
      losses: 7,
      ties: 0,
      winPer: 0.708,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 18,
      losses: 17,
      ties: 1,
      winPer: 0.514,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 11,
      losses: 13,
      ties: 0,
      winPer: 0.458,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 9,
      losses: 12,
      ties: 3,
      winPer: 0.438,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 13,
      losses: 20,
      ties: 3,
      winPer: 0.403,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 12,
      losses: 21,
      ties: 3,
      winPer: 0.375,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 12,
      losses: 24,
      ties: 0,
      winPer: 0.333,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 7,
      losses: 17,
      ties: 0,
      winPer: 0.292,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Joshua Apostol",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 214.8,
      pointsAgainst: 126.6,
      pointsDiff: 88.2,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 106.8,
      pointsAgainst: 53.7,
      pointsDiff: 53.1,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 106.3,
      pointsAgainst: 92,
      pointsDiff: 14.3,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 67.9,
      pointsAgainst: 63.3,
      pointsDiff: 4.6,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 201.7,
      pointsAgainst: 195.3,
      pointsDiff: 6.4,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 181.5,
      pointsAgainst: 195.8,
      pointsDiff: -14.3,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 88.9,
      pointsAgainst: 118.3,
      pointsDiff: -29.4,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 129.3,
      pointsAgainst: 175.3,
      pointsDiff: -46,
    },
    {
      ownerNames: "Tim Fong",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 79.7,
      pointsAgainst: 134.9,
      pointsDiff: -55.2,
    },
  ],
};
