const json = {
  year: "2016",
  totalMatchups: [
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.722,
      baseballWinPer: 0.569,
      footballWinPer: 1,
      totalWinPer: 0.764,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.667,
      baseballWinPer: 0.833,
      footballWinPer: 0.5,
      totalWinPer: 0.667,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.444,
      baseballWinPer: 0.417,
      footballWinPer: 1,
      totalWinPer: 0.62,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.556,
      baseballWinPer: 0.5,
      footballWinPer: 0.5,
      totalWinPer: 0.519,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.778,
      baseballWinPer: 0.583,
      footballWinPer: 0,
      totalWinPer: 0.454,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.944,
      baseballWinPer: 0.396,
      footballWinPer: 0,
      totalWinPer: 0.447,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.556,
      baseballWinPer: 0.597,
      footballWinPer: 0,
      totalWinPer: 0.384,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.667,
      baseballWinPer: 0.417,
      footballWinPer: 0,
      totalWinPer: 0.361,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.528,
      baseballWinPer: 0.375,
      footballWinPer: 0,
      totalWinPer: 0.301,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Wesley Chipeco",
      wins: 17,
      losses: 1,
      ties: 0,
      winPer: 0.944,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 14,
      losses: 4,
      ties: 0,
      winPer: 0.778,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 12,
      losses: 4,
      ties: 2,
      winPer: 0.722,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Tim Fong",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Nick Wang",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 9,
      losses: 8,
      ties: 1,
      winPer: 0.528,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Tim Fong",
      wins: 19,
      losses: 3,
      ties: 2,
      winPer: 0.833,
    },
    {
      ownerNames: "Nick Wang",
      wins: 20,
      losses: 13,
      ties: 3,
      winPer: 0.597,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 19,
      losses: 13,
      ties: 4,
      winPer: 0.583,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 19,
      losses: 14,
      ties: 3,
      winPer: 0.569,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 16,
      losses: 16,
      ties: 4,
      winPer: 0.5,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 10,
      losses: 14,
      ties: 0,
      winPer: 0.417,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 9,
      losses: 13,
      ties: 2,
      winPer: 0.417,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 7,
      losses: 12,
      ties: 5,
      winPer: 0.396,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 8,
      losses: 14,
      ties: 2,
      winPer: 0.375,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Marcus Lam",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 202.3,
      pointsAgainst: 149.5,
      pointsDiff: 52.8,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 109.7,
      pointsAgainst: 91,
      pointsDiff: 18.7,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 191.7,
      pointsAgainst: 153.9,
      pointsDiff: 37.8,
    },
    {
      ownerNames: "Tim Fong",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 208.2,
      pointsAgainst: 187.1,
      pointsDiff: 21.1,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 95.7,
      pointsAgainst: 101.8,
      pointsDiff: -6.1,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 1,
      pointsFor: 79.5,
      pointsAgainst: 94.1,
      pointsDiff: -14.6,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 99.3,
      pointsAgainst: 128.2,
      pointsDiff: -16.8,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 175.5,
      pointsAgainst: 222.2,
      pointsDiff: -46.7,
    },
    {
      ownerNames: "Nick Wang",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 53.7,
      pointsAgainst: 106.8,
      pointsDiff: -53.1,
    },
  ],
};
