const json = {
  year: "2016",
  totalMatchups: [
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.833,
      baseballWinPer: 0.681,
      footballWinPer: 1,
      totalWinPer: 0.838,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.833,
      baseballWinPer: 0.521,
      footballWinPer: 1,
      totalWinPer: 0.785,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.667,
      baseballWinPer: 0.222,
      footballWinPer: 1,
      totalWinPer: 0.63,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.5,
      baseballWinPer: 0.25,
      footballWinPer: 1,
      totalWinPer: 0.583,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.286,
      baseballWinPer: 0.389,
      footballWinPer: 1,
      totalWinPer: 0.558,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.444,
      baseballWinPer: 0.208,
      footballWinPer: 1,
      totalWinPer: 0.551,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.278,
      baseballWinPer: 0.292,
      footballWinPer: 1,
      totalWinPer: 0.523,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.333,
      baseballWinPer: 0.167,
      footballWinPer: 0.5,
      totalWinPer: 0.333,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.444,
      baseballWinPer: 0.271,
      footballWinPer: 0,
      totalWinPer: 0.238,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Wesley Chipeco",
      wins: 15,
      losses: 3,
      ties: 0,
      winPer: 0.833,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 15,
      losses: 3,
      ties: 0,
      winPer: 0.833,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 4,
      losses: 14,
      ties: 0,
      winPer: 0.286,
    },
    {
      ownerNames: "Nick Wang",
      wins: 5,
      losses: 13,
      ties: 0,
      winPer: 0.278,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Wesley Chipeco",
      wins: 23,
      losses: 10,
      ties: 3,
      winPer: 0.681,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 11,
      losses: 10,
      ties: 3,
      winPer: 0.521,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 13,
      losses: 21,
      ties: 2,
      winPer: 0.389,
    },
    {
      ownerNames: "Nick Wang",
      wins: 7,
      losses: 17,
      ties: 0,
      winPer: 0.292,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 6,
      losses: 17,
      ties: 1,
      winPer: 0.271,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 8,
      losses: 26,
      ties: 2,
      winPer: 0.25,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 6,
      losses: 26,
      ties: 4,
      winPer: 0.222,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 4,
      losses: 18,
      ties: 2,
      winPer: 0.208,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 3,
      losses: 19,
      ties: 2,
      winPer: 0.167,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Nick Wang",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 134.9,
      pointsAgainst: 79.7,
      pointsDiff: 55.2,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 216.6,
      pointsAgainst: 178.4,
      pointsDiff: 38.2,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 231.6,
      pointsAgainst: 194.9,
      pointsDiff: 36.7,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 124.1,
      pointsAgainst: 91.5,
      pointsDiff: 32.6,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 107.3,
      pointsAgainst: 85.4,
      pointsDiff: 21.9,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 129.4,
      pointsAgainst: 111.6,
      pointsDiff: 17.8,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 109.3,
      pointsAgainst: 94,
      pointsDiff: 15.3,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 187.1,
      pointsAgainst: 208.2,
      pointsDiff: -21.1,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 167.9,
      pointsAgainst: 169.3,
      pointsDiff: -1.4,
    },
  ],
};
