const json = {
  year: "2016",
  totalMatchups: [
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.361,
      baseballWinPer: 0.514,
      footballWinPer: 1,
      totalWinPer: 0.625,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.222,
      baseballWinPer: 0.472,
      footballWinPer: 1,
      totalWinPer: 0.565,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.222,
      baseballWinPer: 0.458,
      footballWinPer: 1,
      totalWinPer: 0.56,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.222,
      baseballWinPer: 0.417,
      footballWinPer: 1,
      totalWinPer: 0.546,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.583,
      baseballWinPer: 0.542,
      footballWinPer: 0.5,
      totalWinPer: 0.542,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.611,
      baseballWinPer: 0.542,
      footballWinPer: 0,
      totalWinPer: 0.384,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.222,
      baseballWinPer: 0.375,
      footballWinPer: 0.5,
      totalWinPer: 0.366,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.389,
      baseballWinPer: 0.375,
      footballWinPer: 0,
      totalWinPer: 0.255,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.167,
      baseballWinPer: 0.479,
      footballWinPer: 0,
      totalWinPer: 0.215,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 11,
      losses: 7,
      ties: 0,
      winPer: 0.611,
    },
    {
      ownerNames: "Nick Wang",
      wins: 10,
      losses: 7,
      ties: 1,
      winPer: 0.583,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 7,
      losses: 11,
      ties: 0,
      winPer: 0.389,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 6,
      losses: 11,
      ties: 1,
      winPer: 0.361,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 4,
      losses: 14,
      ties: 0,
      winPer: 0.222,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 4,
      losses: 14,
      ties: 0,
      winPer: 0.222,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 4,
      losses: 14,
      ties: 0,
      winPer: 0.222,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 4,
      losses: 14,
      ties: 0,
      winPer: 0.222,
    },
    {
      ownerNames: "Tim Fong",
      wins: 3,
      losses: 15,
      ties: 0,
      winPer: 0.167,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Nick Wang",
      wins: 13,
      losses: 11,
      ties: 0,
      winPer: 0.542,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 12,
      losses: 10,
      ties: 2,
      winPer: 0.542,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 17,
      losses: 16,
      ties: 3,
      winPer: 0.514,
    },
    {
      ownerNames: "Tim Fong",
      wins: 10,
      losses: 11,
      ties: 3,
      winPer: 0.479,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 17,
      losses: 19,
      ties: 0,
      winPer: 0.472,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 11,
      losses: 13,
      ties: 0,
      winPer: 0.458,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 13,
      losses: 19,
      ties: 4,
      winPer: 0.417,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 12,
      losses: 21,
      ties: 3,
      winPer: 0.375,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 8,
      losses: 14,
      ties: 2,
      winPer: 0.375,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Marcus Lam",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 114.4,
      pointsAgainst: 84.3,
      pointsDiff: 30.1,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 189.7,
      pointsAgainst: 164,
      pointsDiff: 25.7,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 219.2,
      pointsAgainst: 195.9,
      pointsDiff: 23.3,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 101.8,
      pointsAgainst: 95.7,
      pointsDiff: 6.1,
    },
    {
      ownerNames: "Nick Wang",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 195.3,
      pointsAgainst: 201.7,
      pointsDiff: -6.4,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 245.9,
      pointsAgainst: 253.1,
      pointsDiff: -7.2,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 104.6,
      pointsAgainst: 115.9,
      pointsDiff: -11.3,
    },
    {
      ownerNames: "Tim Fong",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 85.4,
      pointsAgainst: 107.3,
      pointsDiff: -21.9,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 77.4,
      pointsAgainst: 121.3,
      pointsDiff: -43.9,
    },
  ],
};
