const json = {
  year: "2016",
  totalMatchups: [
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.611,
      baseballWinPer: 0.625,
      footballWinPer: 1,
      totalWinPer: 0.745,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.167,
      baseballWinPer: 0.583,
      footballWinPer: 1,
      totalWinPer: 0.583,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.056,
      baseballWinPer: 0.604,
      footballWinPer: 1,
      totalWinPer: 0.553,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.417,
      baseballWinPer: 0.347,
      footballWinPer: 0.5,
      totalWinPer: 0.421,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.333,
      baseballWinPer: 0.417,
      footballWinPer: 0.5,
      totalWinPer: 0.417,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.25,
      baseballWinPer: 0.486,
      footballWinPer: 0,
      totalWinPer: 0.245,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.167,
      baseballWinPer: 0.563,
      footballWinPer: 0,
      totalWinPer: 0.243,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.278,
      baseballWinPer: 0.292,
      footballWinPer: 0,
      totalWinPer: 0.19,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.167,
      baseballWinPer: 0.319,
      footballWinPer: 0.0,
      totalWinPer: 0.162,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Wayne Fong",
      wins: 11,
      losses: 7,
      ties: 0,
      winPer: 0.611,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 7,
      losses: 10,
      ties: 1,
      winPer: 0.417,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 5,
      losses: 13,
      ties: 0,
      winPer: 0.583,
    },
    {
      ownerNames: "Nick Wang",
      wins: 4,
      losses: 13,
      ties: 1,
      winPer: 0.25,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 3,
      losses: 15,
      ties: 0,
      winPer: 0.167,
    },
    {
      ownerNames: "Tim Fong",
      wins: 3,
      losses: 15,
      ties: 0,
      winPer: 0.167,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 2,
      losses: 14,
      ties: 2,
      winPer: 0.167,
    },
    {
      ownerNames: "Ryan Tommimitsu",
      wins: 1,
      losses: 17,
      ties: 0,
      winPer: 0.056,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Wayne Fong",
      wins: 21,
      losses: 12,
      ties: 3,
      winPer: 0.625,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 12,
      losses: 7,
      ties: 5,
      winPer: 0.604,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 13,
      losses: 9,
      ties: 2,
      winPer: 0.583,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 13,
      losses: 10,
      ties: 1,
      winPer: 0.563,
    },
    {
      ownerNames: "Nick Wang",
      wins: 17,
      losses: 18,
      ties: 1,
      winPer: 0.486,
    },
    {
      ownerNames: "Kevin Okamoto, Nick Wang",
      wins: 9,
      losses: 13,
      ties: 2,
      winPer: 0.417,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 10,
      losses: 23,
      ties: 3,
      winPer: 0.347,
    },
    {
      ownerNames: "Tim Fong",
      wins: 10,
      losses: 23,
      ties: 3,
      winPer: 0.319,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 6,
      losses: 16,
      ties: 2,
      winPer: 0.333,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 222.2,
      pointsAgainst: 175.5,
      pointsDiff: 46.7,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 121.3,
      pointsAgainst: 77.4,
      pointsDiff: 43.9,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 93.2,
      pointsAgainst: 71.4,
      pointsDiff: 21.8,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 195.7,
      pointsAgainst: 166.1,
      pointsDiff: 29.6,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 200.5,
      pointsAgainst: 179.2,
      pointsDiff: 21.3,
    },
    {
      ownerNames: "Nick Wang",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 63.3,
      pointsAgainst: 67.9,
      pointsDiff: -4.6,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 79.5,
      pointsAgainst: 94.1,
      pointsDiff: -14.6,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 80.2,
      pointsAgainst: 97,
      pointsDiff: -16.8,
    },
    {
      ownerNames: "Tim Fong",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 178.4,
      pointsAgainst: 216.6,
      pointsDiff: -38.2,
    },
  ],
};
