export const SCRAPE_H2H_BASEBALL_STANDINGS_START =
  "SCRAPE_H2H_BASEBALL_STANDINGS_START";
export const SCRAPE_H2H_BASEBALL_STANDINGS_SUCCESS =
  "SCRAPE_H2H_BASEBALL_STANDINGS_SUCCESS";
export const SCRAPE_H2H_BASEBALL_STANDINGS_FAILED =
  "SCRAPE_H2H_BASEBALL_STANDINGS_FAILED";

export const SCRAPE_ROTO_BASEBALL_STANDINGS_START =
  "SCRAPE_ROTO_BASEBALL_STANDINGS_START";
export const SCRAPE_ROTO_BASEBALL_STANDINGS_SUCCESS =
  "SCRAPE_ROTO_BASEBALL_STANDINGS_SUCCESS";
export const SCRAPE_ROTO_BASEBALL_STANDINGS_FAILED =
  "SCRAPE_ROTO_BASEBALL_STANDINGS_FAILED";

export const SAVE_SCRAPED_H2H_STANDINGS = "SAVE_SCRAPED_H2H_STANDINGS";
export const SAVE_EXISTING_H2H_STANDINGS = "SAVE_EXISTING_H2H_STANDINGS";
export const SAVE_SCRAPED_ROTO_STATS = "SAVE_SCRAPED_ROTO_STATS";
export const SAVE_EXISTING_ROTO_STATS = "SAVE_EXISTING_ROTO_STATS";
export const SAVE_SCRAPED_ROTO_STANDINGS = "SAVE_SCRAPED_ROTO_STANDINGS";
export const SAVE_EXISTING_ROTO_STANDINGS = "SAVE_EXISTING_ROTO_STANDINGS";
export const SAVE_SCRAPED_TRIFECTA_STANDINGS =
  "SAVE_SCRAPED_TRIFECTA_STANDINGS";
export const SAVE_EXISTING_TRIFECTA_STANDINGS =
  "SAVE_EXISTING_TRIFECTA_STANDINGS";

export const SET_LAST_SCRAPED = "LAST_SCRAPED";

export const SORT_TABLE = "SORT_TABLE";
