const tableDefaultSortDirections = {
  trifectaStandings: {
    h2hTrifectaPoints: true,
    top5Bottom5TrifectaPoints: true,
    trifectaPoints: true,
    playoffPoints: true,
    totalTrifectaPoints: true,
  },
  h2hStandings: {
    wins: true,
    losses: true,
    ties: true,
    winPer: true,
    pointsFor: true,
    pointsAgainst: true,
    h2hTrifectaPoints: true,
  },
  top5Bottom5Standings: {
    week1: true,
    week2: true,
    week3: true,
    week4: true,
    week5: true,
    week6: true,
    week7: true,
    week8: true,
    week9: true,
    week10: true,
    week11: true,
    week12: true,
    week13: true,
    wins: true,
    losses: true,
    winPer: true,
    top5Bottom5TrifectaPoints: true,
  },
  footballStandings: {
    wins: true,
    losses: true,
    ties: true,
    winPer: true,
    pointsFor: true,
    pointsAgainst: true,
    trifectaPoints: true,
    playoffPoints: true,
    totalTrifectaPoints: true,
  },
};

export { tableDefaultSortDirections };
