export const SCRAPE_BASKETBALL_STANDINGS_START =
  "SCRAPE_BASKETBALL_STANDINGS_START";
export const SCRAPE_BASKETBALL_STANDINGS_SUCCESS =
  "SCRAPE_BASKETBALL_STANDINGS_SUCCESS";
export const SCRAPE_BASKETBALL_STANDINGS_FAILED =
  "SCRAPE_BASKETBALL_STANDINGS_FAILED";

export const SAVE_SCRAPED_H2H_STANDINGS = "SAVE_SCRAPED_H2H_STANDINGS";
export const SAVE_SCRAPED_ROTO_STATS = "SAVE_SCRAPED_ROTO_STATS";
export const SAVE_SCRAPED_ROTO_STANDINGS = "SAVE_SCRAPED_ROTO_STANDINGS";
export const SAVE_SCRAPED_TRIFECTA_STANDINGS =
  "SAVE_SCRAPED_TRIFECTA_STANDINGS";
export const SAVE_EXISTING_H2H_STANDINGS = "SAVE_EXISTING_H2H_STANDINGS";
export const SAVE_EXISTING_ROTO_STATS = "SAVE_EXISTING_ROTO_STATS";
export const SAVE_EXISTING_ROTO_STANDINGS = "SAVE_EXISTING_ROTO_STANDINGS";
export const SAVE_EXISTING_TRIFECTA_STANDINGS =
  "SAVE_EXISTING_TRIFECTA_STANDINGS";
export const SAVE_EXISTING_BASKETBALL_STANDINGS =
  "SAVE_EXISTING_BASKETBALL_STANDINGS";

export const SORT_BASKETBALL_STANDINGS_TABLE =
  "SORT_BASKETBALL_STANDINGS_TABLE";
export const SET_BASKETBALL_STANDINGS_LAST_SCRAPED =
  "SET_BASKETBALL_STANDINGS_LAST_SCRAPED";
