export const SCRAPE_BASKETBALL_STANDINGS_START =
  "SCRAPE_BASKETBALL_STANDINGS_START";
export const SCRAPE_BASKETBALL_STANDINGS_SUCCESS =
  "SCRAPE_BASKETBALL_STANDINGS_SUCCESS";
export const SCRAPE_BASKETBALL_STANDINGS_FAILED =
  "SCRAPE_BASKETBALL_STANDINGS_FAILED";
