export const SCRAPE_BASKETBALL_STANDINGS_START =
  "SCRAPE_BASKETBALL_STANDINGS_START";
export const SCRAPE_BASKETBALL_STANDINGS_SUCCESS =
  "SCRAPE_BASKETBALL_STANDINGS_SUCCESS";
export const SCRAPE_BASKETBALL_STANDINGS_FAILED =
  "SCRAPE_BASKETBALL_STANDINGS_FAILED";

export const SAVE_BASKETBALL_STANDINGS = "SAVE_BASKETBALL_STANDINGS";
export const SORT_TABLE = "SORT_TABLE";
export const SET_LAST_SCRAPED = "SET_LAST_SCRAPED";
