const json = {
  year: "2017",
  totalMatchups: [
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.5,
      baseballWinPer: 0.396,
      footballWinPer: 1,
      totalWinPer: 0.632,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.667,
      baseballWinPer: 0.208,
      footballWinPer: 1,
      totalWinPer: 0.625,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.5,
      baseballWinPer: 0.375,
      footballWinPer: 1,
      totalWinPer: 0.625,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.472,
      baseballWinPer: 0.208,
      footballWinPer: 1,
      totalWinPer: 0.56,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.5,
      baseballWinPer: 0.833,
      footballWinPer: 0,
      totalWinPer: 0.444,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.528,
      baseballWinPer: 0.833,
      footballWinPer: 0,
      totalWinPer: 0.364,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.361,
      baseballWinPer: 0.583,
      footballWinPer: 0,
      totalWinPer: 0.315,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.333,
      baseballWinPer: 0.431,
      footballWinPer: 0,
      totalWinPer: 0.255,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.417,
      baseballWinPer: 0.319,
      footballWinPer: 0,
      totalWinPer: 0.245,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Joshua Aguirre",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 9,
      losses: 8,
      ties: 1,
      winPer: 0.528,
    },
    {
      ownerNames: "Tim Fong",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Nick Wang",
      wins: 8,
      losses: 8,
      ties: 2,
      winPer: 0.5,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 8,
      losses: 9,
      ties: 1,
      winPer: 0.472,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 7,
      losses: 10,
      ties: 1,
      winPer: 0.417,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 6,
      losses: 11,
      ties: 1,
      winPer: 0.361,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Nick Wang",
      wins: 20,
      losses: 4,
      ties: 0,
      winPer: 0.833,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 14,
      losses: 10,
      ties: 0,
      winPer: 0.583,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 13,
      losses: 10,
      ties: 1,
      winPer: 0.563,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 14,
      losses: 19,
      ties: 3,
      winPer: 0.431,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 9,
      losses: 14,
      ties: 1,
      winPer: 0.396,
    },
    {
      ownerNames: "Tim Fong",
      wins: 12,
      losses: 21,
      ties: 3,
      winPer: 0.375,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 10,
      losses: 23,
      ties: 3,
      winPer: 0.319,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 5,
      losses: 19,
      ties: 0,
      winPer: 0.208,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 5,
      losses: 26,
      ties: 5,
      winPer: 0.354,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Joshua Aguirre",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 201,
      pointsAgainst: 151.3,
      pointsDiff: 47.7,
    },
    {
      ownerNames: "Tim Fong",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 113.4,
      pointsAgainst: 67.2,
      pointsDiff: 46.2,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 133.8,
      pointsAgainst: 94.2,
      pointsDiff: 39.6,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 107.2,
      pointsAgainst: 80.6,
      pointsDiff: 26.6,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 75.9,
      pointsAgainst: 99.6,
      pointsDiff: -23.7,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 162.1,
      pointsAgainst: 201.2,
      pointsDiff: -39.1,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 173.8,
      pointsAgainst: 216.3,
      pointsDiff: -42.5,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 64.6,
      pointsAgainst: 127.2,
      pointsDiff: -62.6,
    },
    {
      ownerNames: "Nick Wang",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 153,
      pointsAgainst: 219,
      pointsDiff: -66,
    },
  ],
};
