const json = {
  year: "2017",
  totalMatchups: [
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.444,
      baseballWinPer: 0.764,
      footballWinPer: 1,
      totalWinPer: 0.736,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.556,
      baseballWinPer: 0.521,
      footballWinPer: 1,
      totalWinPer: 0.692,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.5,
      baseballWinPer: 0.514,
      footballWinPer: 1,
      totalWinPer: 0.671,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.472,
      baseballWinPer: 0.438,
      footballWinPer: 1,
      totalWinPer: 0.637,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.611,
      baseballWinPer: 0.5,
      footballWinPer: 1,
      totalWinPer: 0.537,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.722,
      baseballWinPer: 0.583,
      footballWinPer: 0,
      totalWinPer: 0.435,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.611,
      baseballWinPer: 0.597,
      footballWinPer: 0,
      totalWinPer: 0.403,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.389,
      baseballWinPer: 0.625,
      footballWinPer: 0,
      totalWinPer: 0.338,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.472,
      baseballWinPer: 0.458,
      footballWinPer: 0,
      totalWinPer: 0.31,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Tim Fong",
      wins: 13,
      losses: 5,
      ties: 0,
      winPer: 0.722,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 11,
      losses: 7,
      ties: 0,
      winPer: 0.611,
    },
    {
      ownerNames: "Nick Wang",
      wins: 11,
      losses: 7,
      ties: 0,
      winPer: 0.611,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 8,
      losses: 9,
      ties: 1,
      winPer: 0.472,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 8,
      losses: 9,
      ties: 1,
      winPer: 0.472,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 7,
      losses: 11,
      ties: 0,
      winPer: 0.389,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Wayne Fong",
      wins: 26,
      losses: 7,
      ties: 3,
      winPer: 0.764,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 14,
      losses: 8,
      ties: 2,
      winPer: 0.625,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 20,
      losses: 13,
      ties: 3,
      winPer: 0.597,
    },
    {
      ownerNames: "Tim Fong",
      wins: 12,
      losses: 8,
      ties: 4,
      winPer: 0.583,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 12,
      losses: 11,
      ties: 1,
      winPer: 0.521,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 18,
      losses: 17,
      ties: 1,
      winPer: 0.514,
    },
    {
      ownerNames: "Nick Wang",
      wins: 16,
      losses: 16,
      ties: 4,
      winPer: 0.5,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 10,
      losses: 12,
      ties: 2,
      winPer: 0.458,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 10,
      losses: 13,
      ties: 1,
      winPer: 0.438,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Wayne Fong",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 196.4,
      pointsAgainst: 133.8,
      pointsDiff: 62.6,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 224.3,
      pointsAgainst: 182.2,
      pointsDiff: 42.1,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 201.2,
      pointsAgainst: 162.1,
      pointsDiff: 39.1,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 87,
      pointsAgainst: 67.2,
      pointsDiff: 19.8,
    },
    {
      ownerNames: "Nick Wang",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 205.3,
      pointsAgainst: 193,
      pointsDiff: 12.3,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 94.7,
      pointsAgainst: 103.3,
      pointsDiff: -8.6,
    },
    {
      ownerNames: "Tim Fong",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 63,
      pointsAgainst: 88.1,
      pointsDiff: -25.1,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 93.4,
      pointsAgainst: 121.5,
      pointsDiff: -28.1,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 57.2,
      pointsAgainst: 97.4,
      pointsDiff: -40.2,
    },
  ],
};
