const json = {
  year: "2017",
  totalMatchups: [
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.333,
      baseballWinPer: 0.604,
      footballWinPer: 1,
      totalWinPer: 0.646,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.361,
      baseballWinPer: 0.5,
      footballWinPer: 1,
      totalWinPer: 0.62,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.167,
      baseballWinPer: 0.688,
      footballWinPer: 1,
      totalWinPer: 0.618,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.556,
      baseballWinPer: 0.25,
      footballWinPer: 1,
      totalWinPer: 0.602,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.444,
      baseballWinPer: 0.486,
      footballWinPer: 0.5,
      totalWinPer: 0.477,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.333,
      baseballWinPer: 0.792,
      footballWinPer: 0,
      totalWinPer: 0.375,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.556,
      baseballWinPer: 0.458,
      footballWinPer: 0,
      totalWinPer: 0.338,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.444,
      baseballWinPer: 0.479,
      footballWinPer: 0,
      totalWinPer: 0.308,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.333,
      baseballWinPer: 0.528,
      footballWinPer: 0,
      totalWinPer: 0.287,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Tim Fong",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Nick Wang",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 6,
      losses: 11,
      ties: 1,
      winPer: 0.361,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 3,
      losses: 15,
      ties: 0,
      winPer: 0.167,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Bryan Kuh",
      wins: 19,
      losses: 5,
      ties: 0,
      winPer: 0.792,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 15,
      losses: 6,
      ties: 3,
      winPer: 0.688,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 14,
      losses: 9,
      ties: 1,
      winPer: 0.604,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 19,
      losses: 17,
      ties: 0,
      winPer: 0.528,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 18,
      losses: 18,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Nick Wang",
      wins: 15,
      losses: 16,
      ties: 5,
      winPer: 0.486,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 11,
      losses: 12,
      ties: 1,
      winPer: 0.479,
    },
    {
      ownerNames: "Tim Fong",
      wins: 16,
      losses: 19,
      ties: 0,
      winPer: 0.458,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 6,
      losses: 18,
      ties: 0,
      winPer: 0.25,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Wayne Fong",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 198.1,
      pointsAgainst: 151.1,
      pointsDiff: 47,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 95.7,
      pointsAgainst: 72.2,
      pointsDiff: 23.5,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 122,
      pointsAgainst: 113.8,
      pointsDiff: 8.2,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 76.9,
      pointsAgainst: 70.1,
      pointsDiff: 6.8,
    },
    {
      ownerNames: "Nick Wang",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 196.5,
      pointsAgainst: 193.5,
      pointsDiff: 3,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 83.8,
      pointsAgainst: 102.9,
      pointsDiff: -19.1,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 182.2,
      pointsAgainst: 224.3,
      pointsDiff: -42.1,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 153.3,
      pointsAgainst: 201,
      pointsDiff: -47.7,
    },
    {
      ownerNames: "Tim Fong",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 72,
      pointsAgainst: 123.6,
      pointsDiff: -51.6,
    },
  ],
};
