const json = {
  year: "2017",
  totalMatchups: [
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.472,
      baseballWinPer: 0.833,
      footballWinPer: 1,
      totalWinPer: 0.768,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.583,
      baseballWinPer: 0.681,
      footballWinPer: 1,
      totalWinPer: 0.755,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.556,
      baseballWinPer: 0.563,
      footballWinPer: 1,
      totalWinPer: 0.706,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.528,
      baseballWinPer: 0.542,
      footballWinPer: 1,
      totalWinPer: 0.69,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.75,
      baseballWinPer: 0.569,
      footballWinPer: 0.5,
      totalWinPer: 0.606,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.667,
      baseballWinPer: 0.597,
      footballWinPer: 0.5,
      totalWinPer: 0.588,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.5,
      baseballWinPer: 0.542,
      footballWinPer: 0.5,
      totalWinPer: 0.514,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.444,
      baseballWinPer: 0.764,
      footballWinPer: 0.0,
      totalWinPer: 0.403,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.5,
      baseballWinPer: 0.667,
      footballWinPer: 0,
      totalWinPer: 0.389,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Tim Fong",
      wins: 13,
      losses: 4,
      ties: 1,
      winPer: 0.75,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 10,
      losses: 7,
      ties: 1,
      winPer: 0.583,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 9,
      losses: 8,
      ties: 1,
      winPer: 0.528,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Nick Wang",
      wins: 8,
      losses: 9,
      ties: 1,
      winPer: 0.472,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Nick Wang",
      wins: 20,
      losses: 4,
      ties: 0,
      winPer: 0.833,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 27,
      losses: 8,
      ties: 1,
      winPer: 0.764,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 23,
      losses: 10,
      ties: 2,
      winPer: 0.681,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 15,
      losses: 7,
      ties: 2,
      winPer: 0.667,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 20,
      losses: 13,
      ties: 3,
      winPer: 0.597,
    },
    {
      ownerNames: "Tim Fong",
      wins: 19,
      losses: 14,
      ties: 3,
      winPer: 0.569,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 13,
      losses: 10,
      ties: 1,
      winPer: 0.563,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 13,
      losses: 11,
      ties: 0,
      winPer: 0.542,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 12,
      losses: 10,
      ties: 2,
      winPer: 0.542,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Bryan Kuh",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 127.2,
      pointsAgainst: 64.6,
      pointsDiff: 62.6,
    },
    {
      ownerNames: "Nick Wang",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 118.2,
      pointsAgainst: 86.2,
      pointsDiff: 32,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 88.2,
      pointsAgainst: 79,
      pointsDiff: 9.2,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 103.3,
      pointsAgainst: 94.7,
      pointsDiff: 8.6,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 186.3,
      pointsAgainst: 154.1,
      pointsDiff: 32.2,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 202.3,
      pointsAgainst: 197.9,
      pointsDiff: 4.4,
    },
    {
      ownerNames: "Tim Fong",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 160.4,
      pointsAgainst: 214.7,
      pointsDiff: -54.3,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 177.3,
      pointsAgainst: 215.2,
      pointsDiff: -37.9,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 177.3,
      pointsAgainst: 215.2,
      pointsDiff: -37.9,
    },
  ],
};
