const json = {
  year: "2017",
  totalMatchups: [
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.639,
      baseballWinPer: 0.646,
      footballWinPer: 1,
      totalWinPer: 0.762,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.667,
      baseballWinPer: 0.472,
      footballWinPer: 1,
      totalWinPer: 0.713,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.556,
      baseballWinPer: 0.5,
      footballWinPer: 1,
      totalWinPer: 0.685,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.667,
      baseballWinPer: 0.188,
      footballWinPer: 1,
      totalWinPer: 0.618,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.389,
      baseballWinPer: 0.403,
      footballWinPer: 1,
      totalWinPer: 0.597,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.333,
      baseballWinPer: 0.458,
      footballWinPer: 1,
      totalWinPer: 0.597,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.5,
      baseballWinPer: 0.458,
      footballWinPer: 0.5,
      totalWinPer: 0.486,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.5,
      baseballWinPer: 0.604,
      footballWinPer: 0.0,
      totalWinPer: 0.368,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.222,
      baseballWinPer: 0.438,
      footballWinPer: 0,
      totalWinPer: 0.22,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Wesley Chipeco",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Tim Fong",
      wins: 11,
      losses: 6,
      ties: 1,
      winPer: 0.639,
    },
    {
      ownerNames: "Nick Wang",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 7,
      losses: 11,
      ties: 0,
      winPer: 0.389,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 4,
      losses: 14,
      ties: 0,
      winPer: 0.222,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Tim Fong",
      wins: 15,
      losses: 8,
      ties: 1,
      winPer: 0.646,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 14,
      losses: 9,
      ties: 1,
      winPer: 0.604,
    },
    {
      ownerNames: "Nick Wang",
      wins: 18,
      losses: 18,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 17,
      losses: 19,
      ties: 0,
      winPer: 0.472,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 15,
      losses: 18,
      ties: 3,
      winPer: 0.458,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 11,
      losses: 13,
      ties: 1,
      winPer: 0.438,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 10,
      losses: 13,
      ties: 1,
      winPer: 0.438,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 13,
      losses: 20,
      ties: 3,
      winPer: 0.403,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 4,
      losses: 19,
      ties: 1,
      winPer: 0.188,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Wesley Chipeco",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 255.9,
      pointsAgainst: 178.7,
      pointsDiff: 77.2,
    },
    {
      ownerNames: "Tim Fong",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 257.8,
      pointsAgainst: 204.1,
      pointsDiff: 53.7,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 121.5,
      pointsAgainst: 93.4,
      pointsDiff: 28.1,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 102.9,
      pointsAgainst: 83.8,
      pointsDiff: 19.1,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 98.8,
      pointsAgainst: 83.6,
      pointsDiff: 15.2,
    },
    {
      ownerNames: "Nick Wang",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 121,
      pointsAgainst: 111.2,
      pointsDiff: 9.8,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 197.9,
      pointsAgainst: 202.3,
      pointsDiff: -4.4,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 80.6,
      pointsAgainst: 107.2,
      pointsDiff: -26.6,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 145.3,
      pointsAgainst: 173.2,
      pointsDiff: -27.9,
    },
  ],
};
