const json = {
  year: "2017",
  totalMatchups: [
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.667,
      baseballWinPer: 0.5,
      footballWinPer: 1,
      totalWinPer: 0.722,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.444,
      baseballWinPer: 0.542,
      footballWinPer: 1,
      totalWinPer: 0.662,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.361,
      baseballWinPer: 0.333,
      footballWinPer: 1,
      totalWinPer: 0.565,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.5,
      baseballWinPer: 0.167,
      footballWinPer: 1,
      totalWinPer: 0.556,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.556,
      baseballWinPer: 0.375,
      footballWinPer: 0.5,
      totalWinPer: 0.477,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.389,
      baseballWinPer: 0.5,
      footballWinPer: 0.5,
      totalWinPer: 0.463,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.444,
      baseballWinPer: 0.5,
      footballWinPer: 0,
      totalWinPer: 0.315,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.528,
      baseballWinPer: 0.167,
      footballWinPer: 0,
      totalWinPer: 0.232,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.333,
      baseballWinPer: 0.25,
      footballWinPer: 0,
      totalWinPer: 0.194,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Tim Fong",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 9,
      losses: 8,
      ties: 1,
      winPer: 0.528,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 8,
      losses: 8,
      ties: 2,
      winPer: 0.5,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 7,
      losses: 11,
      ties: 0,
      winPer: 0.389,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 6,
      losses: 11,
      ties: 1,
      winPer: 0.361,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Wayne Fong",
      wins: 13,
      losses: 11,
      ties: 0,
      winPer: 0.542,
    },
    {
      ownerNames: "Tim Fong",
      wins: 17,
      losses: 17,
      ties: 2,
      winPer: 0.5,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 16,
      losses: 16,
      ties: 4,
      winPer: 0.5,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 18,
      losses: 18,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 7,
      losses: 13,
      ties: 4,
      winPer: 0.375,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 11,
      losses: 23,
      ties: 2,
      winPer: 0.333,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 5,
      losses: 17,
      ties: 2,
      winPer: 0.25,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 4,
      losses: 20,
      ties: 0,
      winPer: 0.167,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 4,
      losses: 20,
      ties: 0,
      winPer: 0.167,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Wayne Fong",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 224.7,
      pointsAgainst: 149.8,
      pointsDiff: 74.9,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 219,
      pointsAgainst: 153,
      pointsDiff: 66,
    },
    {
      ownerNames: "Tim Fong",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 105.5,
      pointsAgainst: 83.7,
      pointsDiff: 21.8,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 94.6,
      pointsAgainst: 94.1,
      pointsDiff: 0.5,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 193.5,
      pointsAgainst: 196.5,
      pointsDiff: -3,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 193,
      pointsAgainst: 205.3,
      pointsDiff: -12.3,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 111.2,
      pointsAgainst: 121,
      pointsDiff: -9.8,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 86.2,
      pointsAgainst: 118.2,
      pointsDiff: -32,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 96.3,
      pointsAgainst: 134.3,
      pointsDiff: -38,
    },
  ],
};
