const json = {
  year: "2017",
  totalMatchups: [
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.667,
      baseballWinPer: 0.75,
      footballWinPer: 1,
      totalWinPer: 0.806,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.778,
      baseballWinPer: 0.563,
      footballWinPer: 1,
      totalWinPer: 0.78,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.667,
      baseballWinPer: 0.569,
      footballWinPer: 1,
      totalWinPer: 0.745,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.361,
      baseballWinPer: 0.681,
      footballWinPer: 1,
      totalWinPer: 0.681,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.611,
      baseballWinPer: 0.375,
      footballWinPer: 1,
      totalWinPer: 0.662,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.417,
      baseballWinPer: 0.396,
      footballWinPer: 1,
      totalWinPer: 0.604,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.333,
      baseballWinPer: 0.403,
      footballWinPer: 0.5,
      totalWinPer: 0.412,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.583,
      baseballWinPer: 0.583,
      footballWinPer: 0,
      totalWinPer: 0.389,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.639,
      baseballWinPer: 0.5,
      footballWinPer: 0,
      totalWinPer: 0.38,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Marcus Lam",
      wins: 14,
      losses: 4,
      ties: 0,
      winPer: 0.778,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Nick Wang",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 11,
      losses: 6,
      ties: 1,
      winPer: 0.639,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 11,
      losses: 7,
      ties: 0,
      winPer: 0.611,
    },
    {
      ownerNames: "Tim Fong",
      wins: 10,
      losses: 7,
      ties: 1,
      winPer: 0.583,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 7,
      losses: 10,
      ties: 1,
      winPer: 0.417,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 6,
      losses: 11,
      ties: 1,
      winPer: 0.361,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Nick Wang",
      wins: 17,
      losses: 5,
      ties: 2,
      winPer: 0.75,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 24,
      losses: 11,
      ties: 1,
      winPer: 0.681,
    },
    {
      ownerNames: "Tim Fong",
      wins: 13,
      losses: 9,
      ties: 2,
      winPer: 0.583,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 19,
      losses: 14,
      ties: 3,
      winPer: 0.569,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 13,
      losses: 10,
      ties: 1,
      winPer: 0.563,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 18,
      losses: 18,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 13,
      losses: 20,
      ties: 3,
      winPer: 0.403,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 9,
      losses: 14,
      ties: 1,
      winPer: 0.396,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 8,
      losses: 14,
      ties: 2,
      winPer: 0.375,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Wesley Chipeco",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 241.1,
      pointsAgainst: 155.5,
      pointsDiff: 85.6,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 97.4,
      pointsAgainst: 57.2,
      pointsDiff: 40.2,
    },
    {
      ownerNames: "Nick Wang",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 134.3,
      pointsAgainst: 96.3,
      pointsDiff: 38,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 173.2,
      pointsAgainst: 145.3,
      pointsDiff: 27.9,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 99.6,
      pointsAgainst: 75.9,
      pointsDiff: 23.7,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 100.8,
      pointsAgainst: 85.4,
      pointsDiff: 15.4,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 154.1,
      pointsAgainst: 186.3,
      pointsDiff: -32.2,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 113.8,
      pointsAgainst: 122,
      pointsDiff: -8.2,
    },
    {
      ownerNames: "Tim Fong",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 182.7,
      pointsAgainst: 241.8,
      pointsDiff: -59.1,
    },
  ],
};
