const json = {
  year: "2017",
  totalMatchups: [
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.444,
      baseballWinPer: 0.542,
      footballWinPer: 1,
      totalWinPer: 0.662,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.333,
      baseballWinPer: 0.604,
      footballWinPer: 1,
      totalWinPer: 0.646,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.417,
      baseballWinPer: 0.417,
      footballWinPer: 1,
      totalWinPer: 0.611,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.278,
      baseballWinPer: 0.417,
      footballWinPer: 1,
      totalWinPer: 0.565,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.333,
      baseballWinPer: 0.521,
      footballWinPer: 0.5,
      totalWinPer: 0.451,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.25,
      baseballWinPer: 0.431,
      footballWinPer: 0.5,
      totalWinPer: 0.394,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.5,
      baseballWinPer: 0.625,
      footballWinPer: 0,
      totalWinPer: 0.375,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.333,
      baseballWinPer: 0.5,
      footballWinPer: 0,
      totalWinPer: 0.278,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.361,
      baseballWinPer: 0.354,
      footballWinPer: 0,
      totalWinPer: 0.238,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Bryan Kuh",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 7,
      losses: 10,
      ties: 1,
      winPer: 0.417,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 6,
      losses: 11,
      ties: 1,
      winPer: 0.361,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
    {
      ownerNames: "Nick Wang",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 5,
      losses: 13,
      ties: 0,
      winPer: 0.278,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 4,
      losses: 13,
      ties: 1,
      winPer: 0.25,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Bryan Kuh",
      wins: 21,
      losses: 12,
      ties: 3,
      winPer: 0.625,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 14,
      losses: 9,
      ties: 1,
      winPer: 0.604,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 19,
      losses: 16,
      ties: 1,
      winPer: 0.542,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 11,
      losses: 10,
      ties: 3,
      winPer: 0.521,
    },
    {
      ownerNames: "Nick Wang",
      wins: 17,
      losses: 17,
      ties: 2,
      winPer: 0.5,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 14,
      losses: 19,
      ties: 3,
      winPer: 0.431,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 8,
      losses: 12,
      ties: 4,
      winPer: 0.417,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 9,
      losses: 13,
      ties: 2,
      winPer: 0.417,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 8,
      losses: 15,
      ties: 1,
      winPer: 0.354,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 241.8,
      pointsAgainst: 182.7,
      pointsDiff: 59.1,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 123.6,
      pointsAgainst: 72,
      pointsDiff: 51.6,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 95.5,
      pointsAgainst: 64,
      pointsDiff: 31.5,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 88.1,
      pointsAgainst: 63,
      pointsDiff: 25.1,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 214.7,
      pointsAgainst: 160.4,
      pointsDiff: 54.3,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 220.7,
      pointsAgainst: 204.9,
      pointsDiff: 15.8,
    },
    {
      ownerNames: "Nick Wang",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 83.7,
      pointsAgainst: 105.5,
      pointsDiff: -21.8,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 67.2,
      pointsAgainst: 113.4,
      pointsDiff: -46.2,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 204.1,
      pointsAgainst: 257.8,
      pointsDiff: -53.7,
    },
  ],
};
