const json = {
  year: "2017",
  totalMatchups: [
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.639,
      baseballWinPer: 0.417,
      footballWinPer: 1,
      totalWinPer: 0.685,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.556,
      baseballWinPer: 0.167,
      footballWinPer: 1,
      totalWinPer: 0.574,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.667,
      baseballWinPer: 0.542,
      footballWinPer: 0,
      totalWinPer: 0.403,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.833,
      baseballWinPer: 0.313,
      footballWinPer: 0,
      totalWinPer: 0.382,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.667,
      baseballWinPer: 0.396,
      footballWinPer: 0,
      totalWinPer: 0.354,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.556,
      baseballWinPer: 0.458,
      footballWinPer: 0,
      totalWinPer: 0.338,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.639,
      baseballWinPer: 0.319,
      footballWinPer: 0,
      totalWinPer: 0.319,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.444,
      baseballWinPer: 0.438,
      footballWinPer: 0,
      totalWinPer: 0.294,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.556,
      baseballWinPer: 0.236,
      footballWinPer: 0,
      totalWinPer: 0.264,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Joshua Aguirre",
      wins: 15,
      losses: 3,
      ties: 0,
      winPer: 0.833,
    },
    {
      ownerNames: "Tim Fong",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 11,
      losses: 6,
      ties: 1,
      winPer: 0.639,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 11,
      losses: 6,
      ties: 1,
      winPer: 0.639,
    },
    {
      ownerNames: "Nick Wang",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Marcus Lam",
      wins: 18,
      losses: 15,
      ties: 3,
      winPer: 0.542,
    },
    {
      ownerNames: "Nick Wang",
      wins: 11,
      losses: 13,
      ties: 0,
      winPer: 0.458,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 10,
      losses: 13,
      ties: 1,
      winPer: 0.438,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 10,
      losses: 14,
      ties: 0,
      winPer: 0.417,
    },
    {
      ownerNames: "Tim Fong",
      wins: 9,
      losses: 14,
      ties: 1,
      winPer: 0.396,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 11,
      losses: 24,
      ties: 1,
      winPer: 0.319,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 6,
      losses: 15,
      ties: 3,
      winPer: 0.313,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 7,
      losses: 26,
      ties: 2,
      winPer: 0.236,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 5,
      losses: 29,
      ties: 2,
      winPer: 0.167,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Bryan Kuh",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 216.3,
      pointsAgainst: 173.8,
      pointsDiff: 42.5,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 91.4,
      pointsAgainst: 72.3,
      pointsDiff: 19.1,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 79,
      pointsAgainst: 88.2,
      pointsDiff: -9.2,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 83.6,
      pointsAgainst: 98.8,
      pointsDiff: -15.2,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 85.4,
      pointsAgainst: 100.8,
      pointsDiff: -15.4,
    },
    {
      ownerNames: "Tim Fong",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 64,
      pointsAgainst: 95.5,
      pointsDiff: -31.5,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 151.1,
      pointsAgainst: 198.1,
      pointsDiff: -47,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 133.8,
      pointsAgainst: 196.4,
      pointsDiff: -62.6,
    },
    {
      ownerNames: "Nick Wang",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 149.8,
      pointsAgainst: 224.7,
      pointsDiff: -74.9,
    },
  ],
};
