const json = {
  year: "2017",
  totalMatchups: [
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.5,
      baseballWinPer: 0.333,
      footballWinPer: 1,
      totalWinPer: 0.611,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.667,
      baseballWinPer: 0.479,
      footballWinPer: 0.5,
      totalWinPer: 0.549,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.528,
      baseballWinPer: 0.792,
      footballWinPer: 0,
      totalWinPer: 0.44,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.639,
      baseballWinPer: 0.667,
      footballWinPer: 0,
      totalWinPer: 0.435,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.444,
      baseballWinPer: 0.833,
      footballWinPer: 0,
      totalWinPer: 0.426,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.583,
      baseballWinPer: 0.604,
      footballWinPer: 0,
      totalWinPer: 0.396,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.333,
      baseballWinPer: 0.813,
      footballWinPer: 0,
      totalWinPer: 0.382,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.667,
      baseballWinPer: 0.396,
      footballWinPer: 0,
      totalWinPer: 0.354,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.5,
      baseballWinPer: 0.486,
      footballWinPer: 0.0,
      totalWinPer: 0.329,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Tim Fong",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Nick Wang",
      wins: 11,
      losses: 6,
      ties: 1,
      winPer: 0.639,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 10,
      losses: 7,
      ties: 1,
      winPer: 0.583,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 9,
      losses: 8,
      ties: 1,
      winPer: 0.528,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Wayne Fong",
      wins: 29,
      losses: 5,
      ties: 2,
      winPer: 0.833,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 19,
      losses: 4,
      ties: 1,
      winPer: 0.813,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 26,
      losses: 5,
      ties: 5,
      winPer: 0.792,
    },
    {
      ownerNames: "Nick Wang",
      wins: 23,
      losses: 11,
      ties: 2,
      winPer: 0.667,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 14,
      losses: 9,
      ties: 1,
      winPer: 0.604,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 17,
      losses: 18,
      ties: 1,
      winPer: 0.486,
    },
    {
      ownerNames: "Tim Fong",
      wins: 10,
      losses: 11,
      ties: 3,
      winPer: 0.479,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 9,
      losses: 14,
      ties: 1,
      winPer: 0.396,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 7,
      losses: 15,
      ties: 2,
      winPer: 0.333,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 215.2,
      pointsAgainst: 177.3,
      pointsDiff: 37.9,
    },
    {
      ownerNames: "Tim Fong",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 204.9,
      pointsAgainst: 220.7,
      pointsDiff: -15.8,
    },
    {
      ownerNames: "Nick Wang",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 94.1,
      pointsAgainst: 94.6,
      pointsDiff: -0.5,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 70.1,
      pointsAgainst: 76.9,
      pointsDiff: -6.8,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 72.3,
      pointsAgainst: 91.4,
      pointsDiff: -19.1,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 67.2,
      pointsAgainst: 87,
      pointsDiff: -19.8,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 94.2,
      pointsAgainst: 133.8,
      pointsDiff: -39.6,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 178.7,
      pointsAgainst: 255.9,
      pointsDiff: -77.2,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 155.5,
      pointsAgainst: 241.1,
      pointsDiff: -85.6,
    },
  ],
};
