export const SCRAPE_FOOTBALL_STANDINGS_START =
  "SCRAPE_FOOTBALL_STANDINGS_START";
export const SCRAPE_FOOTBALL_STANDINGS_SUCCESS =
  "SCRAPE_FOOTBALL_STANDINGS_SUCCESS";
export const SCRAPE_FOOTBALL_STANDINGS_FAILED =
  "SCRAPE_FOOTBALL_STANDINGS_FAILED";

export const SAVE_SCRAPED_H2H_STANDINGS = "SAVE_SCRAPED_H2H_STANDINGS";
export const SAVE_EXISTING_H2H_STANDINGS = "SAVE_EXISTING_H2H_STANDINGS";

export const SAVE_SCRAPED_TOP5_BOTTOM5_STANDINGS =
  "SAVE_SCRAPED_TOP5_BOTTOM5_STANDINGS";
export const SAVE_EXISTING_TOP5_BOTTOM5_STANDINGS =
  "SAVE_EXISTING_TOP5_BOTTOM5_STANDINGS";

export const SAVE_SCRAPED_TRIFECTA_STANDINGS =
  "SAVE_SCRAPED_TRIFECTA_STANDINGS";
export const SAVE_EXISTING_TRIFECTA_STANDINGS =
  "SAVE_EXISTING_TRIFECTA_STANDINGS";

export const SORT_FOOTBALL_STANDINGS_TABLE = "SORT_FOOTBALL_STANDINGS_TABLE";
export const SET_FOOTBALL_STANDINGS_LAST_SCRAPED =
  "SET_FOOTBALL_STANDINGS_LAST_SCRAPED";

export const SAVE_EXISTING_FOOTBALL_STANDINGS =
  "SAVE_EXISTING_FOOTBALL_STANDINGS";
