export const SCRAPE_FOOTBALL_STANDINGS_START =
  "SCRAPE_FOOTBALL_STANDINGS_START";
export const SCRAPE_FOOTBALL_STANDINGS_SUCCESS =
  "SCRAPE_FOOTBALL_STANDINGS_SUCCESS";
export const SCRAPE_FOOTBALL_STANDINGS_FAILED =
  "SCRAPE_FOOTBALL_STANDINGS_FAILED";

export const SAVE_FOOTBALL_STANDINGS = "SAVE_FOOTBALL_STANDINGS";
export const SORT_TABLE = "SORT_TABLE";
export const SET_LAST_SCRAPED = "SET_LAST_SCRAPED";
