export const SAVE_SCRAPED_TOTAL_MATCHUPS =
  "SAVE_SCRAPED_TOTAL_TRIFECTA_MATCHUPS";
export const SAVE_SCRAPED_BASKETBALL_MATCHUPS =
  "SAVE_SCRAPED_BASKETBALL_MATCHUPS";
export const SAVE_SCRAPED_BASEBALL_MATCHUPS = "SAVE_SCRAPED_BASEBALL_MATCHUPS";
export const SAVE_SCRAPED_FOOTBALL_MATCHUPS = "SAVE_SCRAPED_FOOTBALL_MATCHUPS";

export const SAVE_EXISTING_TOTAL_MATCHUPS =
  "SAVE_EXISTING_TOTAL_TRIFECTA_MATCHUPS";
export const SAVE_EXISTING_BASKETBALL_MATCHUPS =
  "SAVE_EXISTING_BASKETBALL_MATCHUPS";
export const SAVE_EXISTING_BASEBALL_MATCHUPS =
  "SAVE_EXISTING_BASEBALL_MATCHUPS";
export const SAVE_EXISTING_FOOTBALL_MATCHUPS =
  "SAVE_EXISTING_FOOTBALL_MATCHUPS";

export const SORT_MATCHUPS = "SORT_MATCHUPS";
export const SET_MATCHUPS_LAST_SCRAPED = "SET_MATCHUPS_LAST_SCRAPED";
