const json = {
  totalMatchups: [
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.556,
      baseballWinPer: 0.771,
      footballWinPer: 1,
      totalWinPer: 0.775,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.583,
      baseballWinPer: 0.417,
      footballWinPer: 1,
      totalWinPer: 0.667,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.611,
      baseballWinPer: 0.736,
      footballWinPer: 0.5,
      totalWinPer: 0.616,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.667,
      baseballWinPer: 0.417,
      footballWinPer: 0.5,
      totalWinPer: 0.528,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.444,
      baseballWinPer: 0.896,
      footballWinPer: 0,
      totalWinPer: 0.447,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.611,
      baseballWinPer: 0.528,
      footballWinPer: 0,
      totalWinPer: 0.38,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.5,
      baseballWinPer: 0.542,
      footballWinPer: 0,
      totalWinPer: 0.347,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.278,
      baseballWinPer: 0.75,
      footballWinPer: 0.0,
      totalWinPer: 0.343,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.556,
      baseballWinPer: 0.354,
      footballWinPer: 0,
      totalWinPer: 0.303,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Joshua Aguirre",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 11,
      losses: 7,
      ties: 0,
      winPer: 0.611,
    },
    {
      ownerNames: "Tim Fong",
      wins: 11,
      losses: 7,
      ties: 0,
      winPer: 0.611,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 10,
      losses: 7,
      ties: 1,
      winPer: 0.583,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Nick Wang",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 5,
      losses: 13,
      ties: 0,
      winPer: 0.278,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Nick Wang",
      wins: 21,
      losses: 2,
      ties: 1,
      winPer: 0.896,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 18,
      losses: 5,
      ties: 1,
      winPer: 0.771,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 18,
      losses: 6,
      ties: 0,
      winPer: 0.75,
    },
    {
      ownerNames: "Tim Fong",
      wins: 25,
      losses: 8,
      ties: 3,
      winPer: 0.736,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 18,
      losses: 15,
      ties: 3,
      winPer: 0.542,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 17,
      losses: 15,
      ties: 4,
      winPer: 0.528,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 9,
      losses: 13,
      ties: 2,
      winPer: 0.417,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 14,
      losses: 20,
      ties: 2,
      winPer: 0.417,
    },
    {
      ownerNames: "Kevin Okamotmo, Joshua Liu",
      wins: 7,
      losses: 14,
      ties: 3,
      winPer: 0.354,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Wesley Chipeco",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 112.5,
      pointsAgainst: 78.9,
      pointsDiff: 33.6,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 118.1,
      pointsAgainst: 88.8,
      pointsDiff: 29.3,
    },
    {
      ownerNames: "Tim Fong",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 219.2,
      pointsAgainst: 199,
      pointsDiff: 20.2,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 187.8,
      pointsAgainst: 188.6,
      pointsDiff: -0.8,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 81,
      pointsAgainst: 100.4,
      pointsDiff: -19.4,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 94.4,
      pointsAgainst: 115.9,
      pointsDiff: -21.5,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 101.2,
      pointsAgainst: 134.7,
      pointsDiff: -33.5,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 161.2,
      pointsAgainst: 209.9,
      pointsDiff: -48.7,
    },
    {
      ownerNames: "Nick Wang",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 168.8,
      pointsAgainst: 218.1,
      pointsDiff: -49.3,
    },
  ],
};
