const json = {
  totalMatchups: [
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.556,
      baseballWinPer: 0.896,
      footballWinPer: 1,
      totalWinPer: 0.817,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.444,
      baseballWinPer: 0.646,
      footballWinPer: 1,
      totalWinPer: 0.697,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.5,
      baseballWinPer: 0.542,
      footballWinPer: 1,
      totalWinPer: 0.681,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.278,
      baseballWinPer: 0.375,
      footballWinPer: 1,
      totalWinPer: 0.551,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.333,
      baseballWinPer: 0.653,
      footballWinPer: 0.5,
      totalWinPer: 0.495,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.611,
      baseballWinPer: 0.486,
      footballWinPer: 0,
      totalWinPer: 0.366,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.444,
      baseballWinPer: 0.604,
      footballWinPer: 0,
      totalWinPer: 0.35,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.444,
      baseballWinPer: 0.597,
      footballWinPer: 0.0,
      totalWinPer: 0.347,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.444,
      baseballWinPer: 0.556,
      footballWinPer: 0,
      totalWinPer: 0.333,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Tim Fong",
      wins: 11,
      losses: 7,
      ties: 0,
      winPer: 0.611,
    },
    {
      ownerNames: "Nick Wang",
      wins: 10,
      losses: 8,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 7,
      losses: 9,
      ties: 2,
      winPer: 0.444,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 5,
      losses: 13,
      ties: 0,
      winPer: 0.278,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Nick Wang",
      wins: 21,
      losses: 2,
      ties: 1,
      winPer: 0.896,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 23,
      losses: 12,
      ties: 1,
      winPer: 0.653,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 14,
      losses: 7,
      ties: 3,
      winPer: 0.646,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 14,
      losses: 9,
      ties: 1,
      winPer: 0.604,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 21,
      losses: 14,
      ties: 1,
      winPer: 0.597,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 18,
      losses: 14,
      ties: 4,
      winPer: 0.556,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 13,
      losses: 11,
      ties: 0,
      winPer: 0.542,
    },
    {
      ownerNames: "Tim Fong",
      wins: 17,
      losses: 18,
      ties: 1,
      winPer: 0.486,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 9,
      losses: 15,
      ties: 0,
      winPer: 0.375,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Wesley Chipeco",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 139.9,
      pointsAgainst: 81.6,
      pointsDiff: 58.3,
    },
    {
      ownerNames: "Nick Wang",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 133.1,
      pointsAgainst: 87.5,
      pointsDiff: 45.6,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 207.9,
      pointsAgainst: 182.3,
      pointsDiff: 25.6,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 2,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 204.7,
      pointsAgainst: 190.5,
      pointsDiff: 14.2,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 226.5,
      pointsAgainst: 215.5,
      pointsDiff: 11,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 86.9,
      pointsAgainst: 90,
      pointsDiff: -3.1,
    },
    {
      ownerNames: "Tim Fong",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 77.8,
      pointsAgainst: 90,
      pointsDiff: -12.2,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 68.9,
      pointsAgainst: 104.8,
      pointsDiff: -35.9,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 146.9,
      pointsAgainst: 258.1,
      pointsDiff: -111.2,
    },
  ],
};
