const json = {
  totalMatchups: [
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.583,
      baseballWinPer: 0.708,
      footballWinPer: 1,
      totalWinPer: 0.764,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.5,
      baseballWinPer: 0.667,
      footballWinPer: 1,
      totalWinPer: 0.722,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.583,
      baseballWinPer: 0.931,
      footballWinPer: 0.5,
      totalWinPer: 0.671,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.556,
      baseballWinPer: 0.396,
      footballWinPer: 1,
      totalWinPer: 0.65,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.389,
      baseballWinPer: 0.472,
      footballWinPer: 1,
      totalWinPer: 0.62,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.722,
      baseballWinPer: 0.625,
      footballWinPer: 0.5,
      totalWinPer: 0.616,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.667,
      baseballWinPer: 0.458,
      footballWinPer: 0.5,
      totalWinPer: 0.542,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.778,
      baseballWinPer: 0.521,
      footballWinPer: 0.0,
      totalWinPer: 0.433,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.444,
      baseballWinPer: 0.38,
      footballWinPer: 0.5,
      totalWinPer: 0.38,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Wayne Fong",
      wins: 14,
      losses: 4,
      ties: 0,
      winPer: 0.778,
    },
    {
      ownerNames: "Tim Fong",
      wins: 13,
      losses: 5,
      ties: 0,
      winPer: 0.722,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 12,
      losses: 6,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Nick Wang",
      wins: 10,
      losses: 7,
      ties: 1,
      winPer: 0.583,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 10,
      losses: 7,
      ties: 1,
      winPer: 0.583,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 9,
      losses: 7,
      ties: 2,
      winPer: 0.556,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 8,
      losses: 10,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 7,
      losses: 11,
      ties: 0,
      winPer: 0.389,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Nick Wang",
      wins: 33,
      losses: 2,
      ties: 1,
      winPer: 0.931,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 17,
      losses: 7,
      ties: 0,
      winPer: 0.708,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 24,
      losses: 12,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Tim Fong",
      wins: 14,
      losses: 8,
      ties: 2,
      winPer: 0.625,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 11,
      losses: 10,
      ties: 3,
      winPer: 0.521,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 15,
      losses: 17,
      ties: 4,
      winPer: 0.472,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 9,
      losses: 11,
      ties: 4,
      winPer: 0.458,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 9,
      losses: 14,
      ties: 1,
      winPer: 0.396,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 6,
      losses: 28,
      ties: 2,
      winPer: 0.194,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Bryan Kuh",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 115.9,
      pointsAgainst: 94.4,
      pointsDiff: 21.5,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 84.5,
      pointsAgainst: 66.5,
      pointsDiff: 18,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 90,
      pointsAgainst: 86.9,
      pointsDiff: 3.1,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 116.3,
      pointsAgainst: 115.9,
      pointsDiff: 0.4,
    },
    {
      ownerNames: "Nick Wang",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 212.6,
      pointsAgainst: 156.8,
      pointsDiff: 55.8,
    },
    {
      ownerNames: "Tim Fong",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 247.8,
      pointsAgainst: 242.8,
      pointsDiff: 5,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 195.3,
      pointsAgainst: 201.5,
      pointsDiff: -6.2,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 209.2,
      pointsAgainst: 243.5,
      pointsDiff: -34.3,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 103.9,
      pointsAgainst: 108.3,
      pointsDiff: -4.4,
    },
  ],
};
