const json = {
  totalMatchups: [
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.389,
      baseballWinPer: 0.514,
      footballWinPer: 1,
      totalWinPer: 0.634,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.333,
      baseballWinPer: 0.569,
      footballWinPer: 1,
      totalWinPer: 0.634,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.278,
      baseballWinPer: 0.514,
      footballWinPer: 0.5,
      totalWinPer: 0.431,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.278,
      baseballWinPer: 0.514,
      footballWinPer: 0.5,
      totalWinPer: 0.384,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.389,
      baseballWinPer: 0.236,
      footballWinPer: 0.5,
      totalWinPer: 0.375,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.528,
      baseballWinPer: 0.479,
      footballWinPer: 0,
      totalWinPer: 0.336,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.5,
      baseballWinPer: 0.458,
      footballWinPer: 0,
      totalWinPer: 0.319,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.5,
      baseballWinPer: 0.333,
      footballWinPer: 0,
      totalWinPer: 0.278,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.167,
      baseballWinPer: 0.521,
      footballWinPer: 0,
      totalWinPer: 0.229,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Nick Wang",
      wins: 9,
      losses: 8,
      ties: 1,
      winPer: 0.528,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 9,
      losses: 9,
      ties: 0,
      winPer: 0.5,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 7,
      losses: 11,
      ties: 0,
      winPer: 0.389,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 7,
      losses: 11,
      ties: 0,
      winPer: 0.389,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 6,
      losses: 12,
      ties: 0,
      winPer: 0.333,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 5,
      losses: 13,
      ties: 0,
      winPer: 0.278,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 5,
      losses: 13,
      ties: 0,
      winPer: 0.278,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 3,
      losses: 15,
      ties: 0,
      winPer: 0.167,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Joshua Aguirre",
      wins: 20,
      losses: 15,
      ties: 1,
      winPer: 0.569,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 12,
      losses: 11,
      ties: 1,
      winPer: 0.521,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 18,
      losses: 17,
      ties: 1,
      winPer: 0.514,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 17,
      losses: 16,
      ties: 3,
      winPer: 0.514,
    },
    {
      ownerNames: "Nick Wang",
      wins: 11,
      losses: 12,
      ties: 1,
      winPer: 0.479,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 10,
      losses: 12,
      ties: 2,
      winPer: 0.458,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 8,
      losses: 14,
      ties: 2,
      winPer: 0.375,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 8,
      losses: 16,
      ties: 0,
      winPer: 0.333,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 8,
      losses: 27,
      ties: 1,
      winPer: 0.236,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Joshua Aguirre",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 113.4,
      pointsAgainst: 85.6,
      pointsDiff: 27.8,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 1,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 90,
      pointsAgainst: 77.8,
      pointsDiff: 12.2,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 179.7,
      pointsAgainst: 96.8,
      pointsDiff: 82.9,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 237.4,
      pointsAgainst: 247.8,
      pointsDiff: -10.4,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 1,
      losses: 1,
      ties: 0,
      winPer: 0.5,
      pointsFor: 199,
      pointsAgainst: 219.2,
      pointsDiff: -20.2,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 97,
      pointsAgainst: 98.6,
      pointsDiff: -1.6,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 100.5,
      pointsAgainst: 126.7,
      pointsDiff: -26.2,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 0,
      losses: 1,
      ties: 0,
      winPer: 0,
      pointsFor: 72.1,
      pointsAgainst: 139.1,
      pointsDiff: -67,
    },
    {
      ownerNames: "Nick Wang",
      wins: 0,
      losses: 2,
      ties: 0,
      winPer: 0,
      pointsFor: 164.4,
      pointsAgainst: 265,
      pointsDiff: -100.6,
    },
  ],
};
