const json = {
  year: "all",
  totalMatchups: [
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.611,
      baseballWinPer: 0.396,
      footballWinPer: 0.833,
      totalWinPer: 0.613,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.537,
      baseballWinPer: 0.49,
      footballWinPer: 667,
      totalWinPer: 0.564,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.537,
      baseballWinPer: 0.62,
      footballWinPer: 0.5,
      totalWinPer: 0.552,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.63,
      baseballWinPer: 0.339,
      footballWinPer: 0.667,
      totalWinPer: 0.545,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.417,
      baseballWinPer: 0.674,
      footballWinPer: 0.333,
      totalWinPer: 0.475,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.481,
      baseballWinPer: 0.571,
      footballWinPer: 0.333,
      totalWinPer: 0.417,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.472,
      baseballWinPer: 0.607,
      footballWinPer: 0,
      totalWinPer: 0.36,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.491,
      baseballWinPer: 0.542,
      footballWinPer: 0,
      totalWinPer: 0.344,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.472,
      baseballWinPer: 0.401,
      footballWinPer: 0,
      totalWinPer: 0.291,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Wesley Chipeco",
      wins: 33,
      losses: 19,
      ties: 2,
      winPer: 0.63,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 33,
      losses: 21,
      ties: 0,
      winPer: 0.611,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 29,
      losses: 25,
      ties: 0,
      winPer: 0.537,
    },
    {
      ownerNames: "Tim Fong",
      wins: 29,
      losses: 25,
      ties: 0,
      winPer: 0.537,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 26,
      losses: 27,
      ties: 1,
      winPer: 0.491,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 26,
      losses: 28,
      ties: 0,
      winPer: 0.481,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 25,
      losses: 28,
      ties: 1,
      winPer: 0.472,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 25,
      losses: 28,
      ties: 1,
      winPer: 0.472,
    },
    {
      ownerNames: "Nick Wang",
      wins: 21,
      losses: 30,
      ties: 3,
      winPer: 0.417,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Nick Wang",
      wins: 46,
      losses: 21,
      ties: 5,
      winPer: 0.674,
    },
    {
      ownerNames: "Tim Fong",
      wins: 63,
      losses: 37,
      ties: 8,
      winPer: 0.62,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 51,
      losses: 33,
      ties: 0,
      winPer: 0.607,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 46,
      losses: 34,
      ties: 4,
      winPer: 0.571,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 42,
      losses: 35,
      ties: 7,
      winPer: 0.542,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 43,
      losses: 45,
      ties: 8,
      winPer: 0.49,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 33,
      losses: 52,
      ties: 8,
      winPer: 0.401,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 27,
      losses: 42,
      ties: 3,
      winPer: 0.396,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 28,
      losses: 59,
      ties: 9,
      winPer: 0.339,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Joshua Aguirre",
      wins: 5,
      losses: 1,
      ties: 0,
      winPer: 0.833,
      pointsFor: 569.1,
      pointsAgainst: 473.6,
      pointsDiff: 95.5,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 2,
      losses: 1,
      ties: 0,
      winPer: 0.667,
      pointsFor: 317.7,
      pointsAgainst: 266.3,
      pointsDiff: 51.4,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 2,
      losses: 1,
      ties: 0,
      winPer: 0.667,
      pointsFor: 320.7,
      pointsAgainst: 302,
      pointsDiff: 18.7,
    },
    {
      ownerNames: "Tim Fong",
      wins: 2,
      losses: 2,
      ties: 0,
      winPer: 0.5,
      pointsFor: 426.6,
      pointsAgainst: 375.5,
      pointsDiff: 51.1,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 1,
      losses: 2,
      ties: 0,
      winPer: 0.333,
      pointsFor: 285,
      pointsAgainst: 293.1,
      pointsDiff: -8.1,
    },
    {
      ownerNames: "Nick Wang",
      wins: 2,
      losses: 4,
      ties: 0,
      winPer: 0.333,
      pointsFor: 497.1,
      pointsAgainst: 566.4,
      pointsDiff: -69.3,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 0,
      losses: 5,
      ties: 0,
      winPer: 0,
      pointsFor: 439,
      pointsAgainst: 540.7,
      pointsDiff: -101.7,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 0,
      losses: 3,
      ties: 0,
      winPer: 0,
      pointsFor: 218.2,
      pointsAgainst: 340.4,
      pointsDiff: -122.2,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 0,
      losses: 6,
      ties: 0,
      winPer: 0,
      pointsFor: 477.8,
      pointsAgainst: 658.5,
      pointsDiff: -180.7,
    },
  ],
};
