const json = {
  year: "all",
  totalMatchups: [
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.537,
      baseballWinPer: 0.411,
      footballWinPer: 1,
      totalWinPer: 0.469,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.537,
      baseballWinPer: 0.41,
      footballWinPer: 1,
      totalWinPer: 0.649,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.481,
      baseballWinPer: 0.583,
      footballWinPer: 0.833,
      totalWinPer: 0.633,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.343,
      baseballWinPer: 0.536,
      footballWinPer: 1,
      totalWinPer: 0.626,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.38,
      baseballWinPer: 0.615,
      footballWinPer: 0.667,
      totalWinPer: 0.554,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.444,
      baseballWinPer: 0.469,
      footballWinPer: 0.333,
      totalWinPer: 0.416,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.389,
      baseballWinPer: 0.604,
      footballWinPer: 0.167,
      totalWinPer: 0.387,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.37,
      baseballWinPer: 0.417,
      footballWinPer: 0.333,
      totalWinPer: 0.373,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.519,
      baseballWinPer: 0.556,
      footballWinPer: 0,
      totalWinPer: 0.358,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 29,
      losses: 25,
      ties: 0,
      winPer: 0.537,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 28,
      losses: 24,
      ties: 2,
      winPer: 0.537,
    },
    {
      ownerNames: "Tim Fong",
      wins: 28,
      losses: 26,
      ties: 0,
      winPer: 0.519,
    },
    {
      ownerNames: "Nick Wang",
      wins: 26,
      losses: 28,
      ties: 0,
      winPer: 0.481,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 24,
      losses: 30,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 21,
      losses: 33,
      ties: 0,
      winPer: 0.389,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 20,
      losses: 33,
      ties: 1,
      winPer: 0.38,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 19,
      losses: 33,
      ties: 2,
      winPer: 0.37,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 18,
      losses: 35,
      ties: 1,
      winPer: 0.343,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Wayne Fong",
      wins: 55,
      losses: 33,
      ties: 8,
      winPer: 0.615,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 42,
      losses: 27,
      ties: 3,
      winPer: 0.604,
    },
    {
      ownerNames: "Nick Wang",
      wins: 51,
      losses: 35,
      ties: 10,
      winPer: 0.583,
    },
    {
      ownerNames: "Tim Fong",
      wins: 57,
      losses: 45,
      ties: 6,
      winPer: 0.556,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 43,
      losses: 37,
      ties: 4,
      winPer: 0.536,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 45,
      losses: 51,
      ties: 0,
      winPer: 0.469,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 28,
      losses: 40,
      ties: 4,
      winPer: 0.417,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 37,
      losses: 54,
      ties: 5,
      winPer: 0.411,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 28,
      losses: 41,
      ties: 3,
      winPer: 0.41,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 3,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 310,
      pointsAgainst: 227.3,
      pointsDiff: 82.7,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 3,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 282.9,
      pointsAgainst: 241.6,
      pointsDiff: 41.3,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 3,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 299.5,
      pointsAgainst: 260.2,
      pointsDiff: 39.3,
    },
    {
      ownerNames: "Nick Wang",
      wins: 5,
      losses: 1,
      ties: 0,
      winPer: 0.833,
      pointsFor: 650.1,
      pointsAgainst: 533.5,
      pointsDiff: 116.6,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 4,
      losses: 2,
      ties: 0,
      winPer: 0.667,
      pointsFor: 578.9,
      pointsAgainst: 561,
      pointsDiff: 17.9,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 1,
      losses: 2,
      ties: 0,
      winPer: 0.333,
      pointsFor: 240.6,
      pointsAgainst: 277.5,
      pointsDiff: -36.9,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 2,
      losses: 4,
      ties: 0,
      winPer: 0.333,
      pointsFor: 581.2,
      pointsAgainst: 642.4,
      pointsDiff: -61.2,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 1,
      losses: 5,
      ties: 0,
      winPer: 0.167,
      pointsFor: 473.6,
      pointsAgainst: 569.1,
      pointsDiff: -95.5,
    },
    {
      ownerNames: "Tim Fong",
      wins: 0,
      losses: 3,
      ties: 0,
      winPer: 0,
      pointsFor: 249.1,
      pointsAgainst: 361.1,
      pointsDiff: -112,
    },
  ],
};
