const json = {
  year: "all",
  totalMatchups: [
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.537,
      baseballWinPer: 0.557,
      footballWinPer: 1,
      totalWinPer: 0.698,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.509,
      baseballWinPer: 0.458,
      footballWinPer: 1,
      totalWinPer: 0.656,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.63,
      baseballWinPer: 0.583,
      footballWinPer: 0.667,
      totalWinPer: 0.627,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.537,
      baseballWinPer: 0.696,
      footballWinPer: 0.5,
      totalWinPer: 0.578,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.435,
      baseballWinPer: 0.571,
      footballWinPer: 0.667,
      totalWinPer: 0.558,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.667,
      baseballWinPer: 0.583,
      footballWinPer: 0.333,
      totalWinPer: 0.528,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.509,
      baseballWinPer: 0.648,
      footballWinPer: 0.4,
      totalWinPer: 0.519,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.583,
      baseballWinPer: 0.506,
      footballWinPer: 0.25,
      totalWinPer: 0.446,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.565,
      baseballWinPer: 0.474,
      footballWinPer: 0,
      totalWinPer: 0.346,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Tim Fong",
      wins: 36,
      losses: 18,
      ties: 0,
      winPer: 0.667,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 33,
      losses: 19,
      ties: 2,
      winPer: 0.63,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 31,
      losses: 22,
      ties: 1,
      winPer: 0.583,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 30,
      losses: 23,
      ties: 1,
      winPer: 0.565,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 29,
      losses: 25,
      ties: 0,
      winPer: 0.537,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 29,
      losses: 25,
      ties: 0,
      winPer: 0.537,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 27,
      losses: 26,
      ties: 1,
      winPer: 0.509,
    },
    {
      ownerNames: "Nick Wang",
      wins: 27,
      losses: 26,
      ties: 1,
      winPer: 0.509,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 23,
      losses: 30,
      ties: 1,
      winPer: 0.435,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Wayne Fong",
      wins: 55,
      losses: 22,
      ties: 7,
      winPer: 0.696,
    },
    {
      ownerNames: "Nick Wang",
      wins: 67,
      losses: 35,
      ties: 6,
      winPer: 0.648,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 40,
      losses: 28,
      ties: 4,
      winPer: 0.583,
    },
    {
      ownerNames: "Tim Fong",
      wins: 45,
      losses: 31,
      ties: 8,
      winPer: 0.583,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 44,
      losses: 32,
      ties: 8,
      winPer: 0.571,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 50,
      losses: 39,
      ties: 7,
      winPer: 0.557,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 40,
      losses: 39,
      ties: 5,
      winPer: 0.506,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 41,
      losses: 36,
      ties: 9,
      winPer: 0.474,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 35,
      losses: 42,
      ties: 7,
      winPer: 0.458,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Bryan Kuh",
      wins: 6,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 658.5,
      pointsAgainst: 477.8,
      pointsDiff: 180.7,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 3,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 345.2,
      pointsAgainst: 238.9,
      pointsDiff: 106.3,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 4,
      losses: 2,
      ties: 0,
      winPer: 0.667,
      pointsFor: 642.4,
      pointsAgainst: 581.2,
      pointsDiff: 61.2,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 2,
      losses: 1,
      ties: 0,
      winPer: 0.667,
      pointsFor: 284.5,
      pointsAgainst: 291.4,
      pointsDiff: -6.9,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 3,
      losses: 3,
      ties: 0,
      winPer: 0.5,
      pointsFor: 629.6,
      pointsAgainst: 600.3,
      pointsDiff: 29.3,
    },
    {
      ownerNames: "Nick Wang",
      wins: 2,
      losses: 3,
      ties: 0,
      winPer: 0.4,
      pointsFor: 436,
      pointsAgainst: 486.9,
      pointsDiff: -50.9,
    },
    {
      ownerNames: "Tim Fong",
      wins: 1,
      losses: 2,
      ties: 0,
      winPer: 0.333,
      pointsFor: 301.3,
      pointsAgainst: 318,
      pointsDiff: -16.7,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 1,
      losses: 3,
      ties: 0,
      winPer: 0.25,
      pointsFor: 395.2,
      pointsAgainst: 404.7,
      pointsDiff: -9.5,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 0,
      losses: 3,
      ties: 0,
      winPer: 0,
      pointsFor: 290.9,
      pointsAgainst: 329.5,
      pointsDiff: -38.6,
    },
  ],
};
