const json = {
  year: "all",
  totalMatchups: [
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.528,
      baseballWinPer: 0.599,
      footballWinPer: 1,
      totalWinPer: 0.709,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.491,
      baseballWinPer: 0.764,
      footballWinPer: 0.667,
      totalWinPer: 0.64,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.639,
      baseballWinPer: 0.578,
      footballWinPer: 0.6,
      totalWinPer: 0.606,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.417,
      baseballWinPer: 0.494,
      footballWinPer: 0.75,
      totalWinPer: 0.554,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.463,
      baseballWinPer: 0.569,
      footballWinPer: 0.6,
      totalWinPer: 0.544,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.481,
      baseballWinPer: 0.583,
      footballWinPer: 0.5,
      totalWinPer: 0.522,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.556,
      baseballWinPer: 0.567,
      footballWinPer: 0.4,
      totalWinPer: 0.518,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.463,
      baseballWinPer: 0.548,
      footballWinPer: 0.5,
      totalWinPer: 0.504,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.463,
      baseballWinPer: 0.611,
      footballWinPer: 0,
      totalWinPer: 0.358,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Tim Fong",
      wins: 34,
      losses: 19,
      ties: 1,
      winPer: 0.639,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 30,
      losses: 24,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 28,
      losses: 25,
      ties: 1,
      winPer: 0.528,
    },
    {
      ownerNames: "Nick Wang",
      wins: 25,
      losses: 26,
      ties: 3,
      winPer: 0.491,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 26,
      losses: 28,
      ties: 0,
      winPer: 0.481,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 25,
      losses: 29,
      ties: 0,
      winPer: 0.463,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 24,
      losses: 28,
      ties: 2,
      winPer: 0.463,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 25,
      losses: 29,
      ties: 0,
      winPer: 0.463,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 22,
      losses: 31,
      ties: 1,
      winPer: 0.417,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Nick Wang",
      wins: 53,
      losses: 15,
      ties: 4,
      winPer: 0.764,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 63,
      losses: 39,
      ties: 6,
      winPer: 0.611,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 52,
      losses: 33,
      ties: 11,
      winPer: 0.599,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 41,
      losses: 27,
      ties: 4,
      winPer: 0.597,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 59,
      losses: 41,
      ties: 8,
      winPer: 0.583,
    },
    {
      ownerNames: "Tim Fong",
      wins: 53,
      losses: 38,
      ties: 5,
      winPer: 0.578,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 39,
      losses: 29,
      ties: 4,
      winPer: 0.569,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 44,
      losses: 36,
      ties: 4,
      winPer: 0.548,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 39,
      losses: 40,
      ties: 5,
      winPer: 0.494,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Bryan Kuh",
      wins: 4,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 447.9,
      pointsAgainst: 319.5,
      pointsDiff: 128.4,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 3,
      losses: 1,
      ties: 0,
      winPer: 0.75,
      pointsFor: 404.7,
      pointsAgainst: 395.2,
      pointsDiff: 9.5,
    },
    {
      ownerNames: "Nick Wang",
      wins: 2,
      losses: 1,
      ties: 0,
      winPer: 0.67,
      pointsFor: 343.3,
      pointsAgainst: 280,
      pointsDiff: 63.3,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 3,
      losses: 2,
      ties: 0,
      winPer: 0.6,
      pointsFor: 484.4,
      pointsAgainst: 456.2,
      pointsDiff: 28.2,
    },
    {
      ownerNames: "Tim Fong",
      wins: 3,
      losses: 2,
      ties: 0,
      winPer: 0.6,
      pointsFor: 407.5,
      pointsAgainst: 472.6,
      pointsDiff: -65.1,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 3,
      losses: 3,
      ties: 0,
      winPer: 0.5,
      pointsFor: 566.7,
      pointsAgainst: 561.3,
      pointsDiff: -5.4,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 2,
      losses: 2,
      ties: 0,
      winPer: 0.5,
      pointsFor: 351,
      pointsAgainst: 441.7,
      pointsDiff: -90.7,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 2,
      losses: 3,
      ties: 0,
      winPer: 0.4,
      pointsFor: 483.3,
      pointsAgainst: 492.5,
      pointsDiff: -9.2,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 0,
      losses: 3,
      ties: 0,
      winPer: 0,
      pointsFor: 227.3,
      pointsAgainst: 310,
      pointsDiff: -82.7,
    },
  ],
};
