const json = {
  year: "all",
  totalMatchups: [
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.62,
      baseballWinPer: 0.714,
      footballWinPer: 0.75,
      totalWinPer: 0.695,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.435,
      baseballWinPer: 0.526,
      footballWinPer: 1,
      totalWinPer: 0.654,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.639,
      baseballWinPer: 0.688,
      footballWinPer: 0.5,
      totalWinPer: 0.609,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.556,
      baseballWinPer: 0.531,
      footballWinPer: 667,
      totalWinPer: 0.584,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.565,
      baseballWinPer: 0.365,
      footballWinPer: 0.667,
      totalWinPer: 0.532,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.63,
      baseballWinPer: 0.5,
      footballWinPer: 0.333,
      totalWinPer: 0.488,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.537,
      baseballWinPer: 0.431,
      footballWinPer: 0.4,
      totalWinPer: 0.456,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.463,
      baseballWinPer: 0.51,
      footballWinPer: 0.333,
      totalWinPer: 0.436,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.389,
      baseballWinPer: 0.44,
      footballWinPer: 0.167,
      totalWinPer: 0.332,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Tim Fong",
      wins: 34,
      losses: 19,
      ties: 1,
      winPer: 0.639,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 34,
      losses: 20,
      ties: 0,
      winPer: 0.63,
    },
    {
      ownerNames: "Nick Wang",
      wins: 33,
      losses: 20,
      ties: 1,
      winPer: 0.62,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 30,
      losses: 23,
      ties: 1,
      winPer: 0.565,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 30,
      losses: 24,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 28,
      losses: 24,
      ties: 2,
      winPer: 0.537,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 25,
      losses: 29,
      ties: 0,
      winPer: 0.463,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 23,
      losses: 30,
      ties: 1,
      winPer: 0.435,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 20,
      losses: 32,
      ties: 2,
      winPer: 0.389,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Nick Wang",
      wins: 68,
      losses: 27,
      ties: 1,
      winPer: 0.714,
    },
    {
      ownerNames: "Tim Fong",
      wins: 47,
      losses: 20,
      ties: 5,
      winPer: 0.688,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 51,
      losses: 45,
      ties: 0,
      winPer: 0.531,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 46,
      losses: 41,
      ties: 9,
      winPer: 0.526,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 45,
      losses: 43,
      ties: 8,
      winPer: 0.51,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 39,
      losses: 39,
      ties: 6,
      winPer: 0.5,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 33,
      losses: 43,
      ties: 8,
      winPer: 0.44,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 29,
      losses: 39,
      ties: 4,
      winPer: 0.431,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 32,
      losses: 58,
      ties: 6,
      winPer: 0.365,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Joshua Apostol",
      wins: 3,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 329.5,
      pointsAgainst: 290.9,
      pointsDiff: 38.6,
    },
    {
      ownerNames: "Nick Wang",
      wins: 3,
      losses: 1,
      ties: 0,
      winPer: 0.75,
      pointsFor: 451.9,
      pointsAgainst: 356.9,
      pointsDiff: 95,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 4,
      losses: 2,
      ties: 0,
      winPer: 0.667,
      pointsFor: 630.4,
      pointsAgainst: 580.7,
      pointsDiff: 49.7,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 2,
      losses: 1,
      ties: 0,
      winPer: 0.667,
      pointsFor: 277.5,
      pointsAgainst: 240.6,
      pointsDiff: 36.9,
    },
    {
      ownerNames: "Tim Fong",
      wins: 3,
      losses: 3,
      ties: 0,
      winPer: 0.5,
      pointsFor: 700.5,
      pointsAgainst: 678.5,
      pointsDiff: 22,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 2,
      losses: 3,
      ties: 0,
      winPer: 0.4,
      pointsFor: 456.2,
      pointsAgainst: 484.4,
      pointsDiff: -28.2,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 1,
      losses: 2,
      ties: 0,
      winPer: 0.333,
      pointsFor: 302,
      pointsAgainst: 320.7,
      pointsDiff: -18.7,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 1,
      losses: 2,
      ties: 0,
      winPer: 0.333,
      pointsFor: 287,
      pointsAgainst: 306.3,
      pointsDiff: -19.3,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 1,
      losses: 5,
      ties: 0,
      winPer: 0.167,
      pointsFor: 504,
      pointsAgainst: 619,
      pointsDiff: -115,
    },
  ],
};
