const json = {
  year: "all",
  totalMatchups: [
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.62,
      baseballWinPer: 0.565,
      footballWinPer: 0.75,
      totalWinPer: 0.645,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.491,
      baseballWinPer: 0.506,
      footballWinPer: 0.8,
      totalWinPer: 0.599,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.593,
      baseballWinPer: 0.407,
      footballWinPer: 0.75,
      totalWinPer: 0.583,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.583,
      baseballWinPer: 0.326,
      footballWinPer: 0.6,
      totalWinPer: 0.503,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.491,
      baseballWinPer: 0.352,
      footballWinPer: 0.6,
      totalWinPer: 0.481,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.509,
      baseballWinPer: 0.236,
      footballWinPer: 0.333,
      totalWinPer: 0.36,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.519,
      baseballWinPer: 0.363,
      footballWinPer: 0.167,
      totalWinPer: 0.349,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.37,
      baseballWinPer: 0.339,
      footballWinPer: 0.333,
      totalWinPer: 0.348,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.38,
      baseballWinPer: 0.286,
      footballWinPer: 0.25,
      totalWinPer: 0.305,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Tim Fong",
      wins: 33,
      losses: 20,
      ties: 1,
      winPer: 0.62,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 31,
      losses: 21,
      ties: 2,
      winPer: 0.593,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 30,
      losses: 21,
      ties: 3,
      winPer: 0.583,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 28,
      losses: 26,
      ties: 0,
      winPer: 0.519,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 26,
      losses: 25,
      ties: 1,
      winPer: 0.509,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 26,
      losses: 27,
      ties: 1,
      winPer: 0.491,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 26,
      losses: 27,
      ties: 1,
      winPer: 0.491,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 20,
      losses: 33,
      ties: 1,
      winPer: 0.38,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 20,
      losses: 34,
      ties: 0,
      winPer: 0.37,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Tim Fong",
      wins: 46,
      losses: 35,
      ties: 3,
      winPer: 0.565,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 39,
      losses: 38,
      ties: 7,
      winPer: 0.506,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 41,
      losses: 61,
      ties: 6,
      winPer: 0.407,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 26,
      losses: 49,
      ties: 9,
      winPer: 0.363,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 35,
      losses: 67,
      ties: 6,
      winPer: 0.352,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 25,
      losses: 52,
      ties: 7,
      winPer: 0.339,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 21,
      losses: 46,
      ties: 5,
      winPer: 0.326,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 27,
      losses: 68,
      ties: 1,
      winPer: 0.286,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 15,
      losses: 53,
      ties: 4,
      winPer: 0.236,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Wayne Fong",
      wins: 4,
      losses: 1,
      ties: 0,
      winPer: 0.8,
      pointsFor: 532.2,
      pointsAgainst: 426.8,
      pointsDiff: 105.4,
    },
    {
      ownerNames: "Tim Fong",
      wins: 3,
      losses: 1,
      ties: 0,
      winPer: 0.75,
      pointsFor: 450.2,
      pointsAgainst: 383,
      pointsDiff: 67.2,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 3,
      losses: 1,
      ties: 0,
      winPer: 0.75,
      pointsFor: 348.8,
      pointsAgainst: 331,
      pointsDiff: 17.8,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 3,
      losses: 2,
      ties: 0,
      winPer: 0.6,
      pointsFor: 458.9,
      pointsAgainst: 395.8,
      pointsDiff: 63.1,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 3,
      losses: 2,
      ties: 0,
      winPer: 0.6,
      pointsFor: 486.9,
      pointsAgainst: 436,
      pointsDiff: 50.9,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 1,
      losses: 2,
      ties: 0,
      winPer: 0.333,
      pointsFor: 281.9,
      pointsAgainst: 302.7,
      pointsDiff: -20.8,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 1,
      losses: 2,
      ties: 0,
      winPer: 0.333,
      pointsFor: 280,
      pointsAgainst: 343.3,
      pointsDiff: -63.3,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 1,
      losses: 3,
      ties: 0,
      winPer: 0.333,
      pointsFor: 356.9,
      pointsAgainst: 451.9,
      pointsDiff: -95,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 1,
      losses: 5,
      ties: 0,
      winPer: 0.167,
      pointsFor: 533.5,
      pointsAgainst: 650.1,
      pointsDiff: -116.6,
    },
  ],
};
