const json = {
  year: "all",
  totalMatchups: [
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.611,
      baseballWinPer: 0.56,
      footballWinPer: 0.833,
      totalWinPer: 0.668,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.63,
      baseballWinPer: 0.661,
      footballWinPer: 0.667,
      totalWinPer: 0.652,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.519,
      baseballWinPer: 0.429,
      footballWinPer: 0.667,
      totalWinPer: 0.538,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.657,
      baseballWinPer: 0.613,
      footballWinPer: 0.333,
      totalWinPer: 0.565,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.509,
      baseballWinPer: 0.634,
      footballWinPer: 0.333,
      totalWinPer: 0.492,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.519,
      baseballWinPer: 0.417,
      footballWinPer: 0.5,
      totalWinPer: 0.478,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.574,
      baseballWinPer: 0.382,
      footballWinPer: 0.333,
      totalWinPer: 0.43,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.509,
      baseballWinPer: 0.429,
      footballWinPer: 0.333,
      totalWinPer: 0.424,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.657,
      baseballWinPer: 0.464,
      footballWinPer: 0,
      totalWinPer: 0.374,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Tim Fong",
      wins: 35,
      losses: 18,
      ties: 1,
      winPer: 0.657,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 35,
      losses: 18,
      ties: 1,
      winPer: 0.657,
    },
    {
      ownerNames: "Nick Wang",
      wins: 34,
      losses: 20,
      ties: 0,
      winPer: 0.634,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 32,
      losses: 20,
      ties: 2,
      winPer: 0.611,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 30,
      losses: 22,
      ties: 2,
      winPer: 0.574,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 28,
      losses: 26,
      ties: 0,
      winPer: 0.519,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 28,
      losses: 26,
      ties: 0,
      winPer: 0.519,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 27,
      losses: 26,
      ties: 1,
      winPer: 0.509,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 27,
      losses: 26,
      ties: 1,
      winPer: 0.509,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Nick Wang",
      wins: 52,
      losses: 25,
      ties: 7,
      winPer: 0.661,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 65,
      losses: 36,
      ties: 7,
      winPer: 0.634,
    },
    {
      ownerNames: "Tim Fong",
      wins: 48,
      losses: 29,
      ties: 7,
      winPer: 0.613,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 43,
      losses: 33,
      ties: 8,
      winPer: 0.56,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 37,
      losses: 43,
      ties: 4,
      winPer: 0.464,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 32,
      losses: 44,
      ties: 8,
      winPer: 0.429,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 34,
      losses: 46,
      ties: 4,
      winPer: 0.429,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 41,
      losses: 59,
      ties: 8,
      winPer: 0.417,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 24,
      losses: 41,
      ties: 7,
      winPer: 0.382,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Marcus Lam",
      wins: 5,
      losses: 1,
      ties: 0,
      winPer: 0.833,
      pointsFor: 619,
      pointsAgainst: 504,
      pointsDiff: 115,
    },
    {
      ownerNames: "Nick Wang",
      wins: 2,
      losses: 1,
      ties: 0,
      winPer: 0.667,
      pointsFor: 302.7,
      pointsAgainst: 281.9,
      pointsDiff: 20.8,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 2,
      losses: 1,
      ties: 0,
      winPer: 0.667,
      pointsFor: 298.1,
      pointsAgainst: 285,
      pointsDiff: 13.1,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 3,
      losses: 3,
      ties: 0,
      winPer: 0.5,
      pointsFor: 561.3,
      pointsAgainst: 566.7,
      pointsDiff: -5.4,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 1,
      losses: 2,
      ties: 0,
      winPer: 0.333,
      pointsFor: 291.4,
      pointsAgainst: 284.5,
      pointsDiff: 6.9,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 2,
      losses: 4,
      ties: 0,
      winPer: 0.333,
      pointsFor: 596.5,
      pointsAgainst: 604.9,
      pointsDiff: -8.4,
    },
    {
      ownerNames: "Tim Fong",
      wins: 2,
      losses: 4,
      ties: 0,
      winPer: 0.33,
      pointsFor: 599.5,
      pointsAgainst: 608.6,
      pointsDiff: -9.1,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 1,
      losses: 2,
      ties: 0,
      winPer: 0.333,
      pointsFor: 273.6,
      pointsAgainst: 299.3,
      pointsDiff: -25.7,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 0,
      losses: 3,
      ties: 0,
      winPer: 0,
      pointsFor: 287.3,
      pointsAgainst: 315.5,
      pointsDiff: -28.2,
    },
  ],
};
