const json = {
  year: "all",
  totalMatchups: [
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.481,
      baseballWinPer: 0.444,
      footballWinPer: 1,
      totalWinPer: 0.642,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.556,
      baseballWinPer: 0.536,
      footballWinPer: 0.6,
      totalWinPer: 0.564,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.444,
      baseballWinPer: 0.549,
      footballWinPer: 0.667,
      totalWinPer: 0.553,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.333,
      baseballWinPer: 0.417,
      footballWinPer: 0.667,
      totalWinPer: 0.472,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.343,
      baseballWinPer: 0.387,
      footballWinPer: 0.667,
      totalWinPer: 0.465,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.463,
      baseballWinPer: 0.37,
      footballWinPer: 0.5,
      totalWinPer: 0.444,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.361,
      baseballWinPer: 0.422,
      footballWinPer: 0.4,
      totalWinPer: 0.394,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.361,
      baseballWinPer: 0.313,
      footballWinPer: 0.5,
      totalWinPer: 0.391,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.38,
      baseballWinPer: 0.435,
      footballWinPer: 0.25,
      totalWinPer: 0.355,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Wesley Chipeco",
      wins: 30,
      losses: 24,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 26,
      losses: 28,
      ties: 0,
      winPer: 0.481,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 25,
      losses: 29,
      ties: 0,
      winPer: 0.463,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 24,
      losses: 30,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Nick Wang",
      wins: 20,
      losses: 33,
      ties: 1,
      winPer: 0.38,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 19,
      losses: 34,
      ties: 1,
      winPer: 0.361,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 19,
      losses: 34,
      ties: 1,
      winPer: 0.361,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 18,
      losses: 35,
      ties: 1,
      winPer: 0.343,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 18,
      losses: 36,
      ties: 0,
      winPer: 0.333,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Wayne Fong",
      wins: 37,
      losses: 30,
      ties: 5,
      winPer: 0.549,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 42,
      losses: 36,
      ties: 6,
      winPer: 0.536,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 45,
      losses: 57,
      ties: 6,
      winPer: 0.444,
    },
    {
      ownerNames: "Nick Wang",
      wins: 35,
      losses: 46,
      ties: 3,
      winPer: 0.435,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 38,
      losses: 53,
      ties: 5,
      winPer: 0.422,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 31,
      losses: 45,
      ties: 8,
      winPer: 0.417,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 29,
      losses: 48,
      ties: 7,
      winPer: 0.387,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 37,
      losses: 65,
      ties: 6,
      winPer: 0.37,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 20,
      losses: 47,
      ties: 5,
      winPer: 0.313,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Joshua Aguirre",
      wins: 3,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 361.1,
      pointsAgainst: 249.1,
      pointsDiff: 112,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 4,
      losses: 2,
      ties: 0,
      winPer: 0.667,
      pointsFor: 608.6,
      pointsAgainst: 487.7,
      pointsDiff: 120.9,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 2,
      losses: 1,
      ties: 0,
      winPer: 0.667,
      pointsFor: 318,
      pointsAgainst: 301.3,
      pointsDiff: 16.7,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 2,
      losses: 1,
      ties: 0,
      winPer: 0.667,
      pointsFor: 274.9,
      pointsAgainst: 288.5,
      pointsDiff: -13.6,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 3,
      losses: 2,
      ties: 0,
      winPer: 0.6,
      pointsFor: 534.3,
      pointsAgainst: 481.9,
      pointsDiff: 52.4,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 3,
      losses: 3,
      ties: 0,
      winPer: 0.5,
      pointsFor: 673.1,
      pointsAgainst: 700.5,
      pointsDiff: -27.4,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 2,
      losses: 2,
      ties: 0,
      winPer: 0.5,
      pointsFor: 375.5,
      pointsAgainst: 426.6,
      pointsDiff: -51.1,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 2,
      losses: 3,
      ties: 0,
      winPer: 0.4,
      pointsFor: 472.6,
      pointsAgainst: 407.5,
      pointsDiff: 65.1,
    },
    {
      ownerNames: "Nick Wang",
      wins: 1,
      losses: 3,
      ties: 0,
      winPer: 0.25,
      pointsFor: 383,
      pointsAgainst: 450.2,
      pointsDiff: -67.2,
    },
  ],
};
