const json = {
  year: "all",
  totalMatchups: [
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.528,
      baseballWinPer: 0.393,
      footballWinPer: 1,
      totalWinPer: 0.64,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.37,
      baseballWinPer: 0.5,
      footballWinPer: 0.667,
      totalWinPer: 0.512,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.491,
      baseballWinPer: 0.366,
      footballWinPer: 0.667,
      totalWinPer: 0.508,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.62,
      baseballWinPer: 0.385,
      footballWinPer: 0.5,
      totalWinPer: 0.502,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.537,
      baseballWinPer: 0.452,
      footballWinPer: 0.5,
      totalWinPer: 0.496,
    },
    {
      ownerNames: "Wesley Chipeco",
      basketballWinPer: 0.435,
      baseballWinPer: 0.25,
      footballWinPer: 0.75,
      totalWinPer: 0.478,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.556,
      baseballWinPer: 0.451,
      footballWinPer: 0.333,
      totalWinPer: 0.447,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.463,
      baseballWinPer: 0.304,
      footballWinPer: 0.5,
      totalWinPer: 0.422,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.509,
      baseballWinPer: 0.494,
      footballWinPer: 0.2,
      totalWinPer: 0.401,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Joshua Aguirre",
      wins: 33,
      losses: 20,
      ties: 1,
      winPer: 0.62,
    },
    {
      ownerNames: "Tim Fong",
      wins: 30,
      losses: 24,
      ties: 0,
      winPer: 0.556,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 29,
      losses: 25,
      ties: 0,
      winPer: 0.537,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 28,
      losses: 25,
      ties: 1,
      winPer: 0.528,
    },
    {
      ownerNames: "Nick Wang",
      wins: 27,
      losses: 26,
      ties: 1,
      winPer: 0.509,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 26,
      losses: 27,
      ties: 1,
      winPer: 0.491,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 25,
      losses: 29,
      ties: 0,
      winPer: 0.463,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 23,
      losses: 30,
      ties: 1,
      winPer: 0.435,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 20,
      losses: 34,
      ties: 0,
      winPer: 0.37,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Marcus Lam",
      wins: 39,
      losses: 39,
      ties: 6,
      winPer: 0.5,
    },
    {
      ownerNames: "Nick Wang",
      wins: 38,
      losses: 39,
      ties: 7,
      winPer: 0.494,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 36,
      losses: 44,
      ties: 4,
      winPer: 0.452,
    },
    {
      ownerNames: "Tim Fong",
      wins: 30,
      losses: 37,
      ties: 5,
      winPer: 0.451,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 33,
      losses: 51,
      ties: 0,
      winPer: 0.393,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 33,
      losses: 55,
      ties: 8,
      winPer: 0.385,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 36,
      losses: 65,
      ties: 7,
      winPer: 0.366,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 22,
      losses: 55,
      ties: 7,
      winPer: 0.304,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 21,
      losses: 69,
      ties: 6,
      winPer: 0.25,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Bryan Kuh",
      wins: 5,
      losses: 0,
      ties: 0,
      winPer: 1,
      pointsFor: 543.4,
      pointsAgainst: 439,
      pointsDiff: 104.4,
    },
    {
      ownerNames: "Wesley Chipeco",
      wins: 3,
      losses: 1,
      ties: 0,
      winPer: 0.75,
      pointsFor: 408.3,
      pointsAgainst: 387.4,
      pointsDiff: 20.9,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 2,
      losses: 1,
      ties: 0,
      winPer: 0.667,
      pointsFor: 299.3,
      pointsAgainst: 273.6,
      pointsDiff: 25.7,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 2,
      losses: 1,
      ties: 0,
      winPer: 0.667,
      pointsFor: 306.3,
      pointsAgainst: 287,
      pointsDiff: 19.3,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 2,
      losses: 2,
      ties: 0,
      winPer: 0.5,
      pointsFor: 441.7,
      pointsAgainst: 351,
      pointsDiff: 90.7,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 3,
      losses: 3,
      ties: 0,
      winPer: 0.5,
      pointsFor: 561,
      pointsAgainst: 578.9,
      pointsDiff: -17.9,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 3,
      losses: 3,
      ties: 0,
      winPer: 0.5,
      pointsFor: 600.3,
      pointsAgainst: 629.6,
      pointsDiff: -29.3,
    },
    {
      ownerNames: "Tim Fong",
      wins: 1,
      losses: 2,
      ties: 0,
      winPer: 0.333,
      pointsFor: 288.5,
      pointsAgainst: 274.9,
      pointsDiff: 13.6,
    },
    {
      ownerNames: "Nick Wang",
      wins: 1,
      losses: 4,
      ties: 0,
      winPer: 0.2,
      pointsFor: 426.8,
      pointsAgainst: 532.2,
      pointsDiff: -105.4,
    },
  ],
};
