const json = {
  year: "all",
  totalMatchups: [
    {
      ownerNames: "Ryan Tomimitsu",
      basketballWinPer: 0.426,
      baseballWinPer: 0.618,
      footballWinPer: 0.667,
      totalWinPer: 0.57,
    },
    {
      ownerNames: "Wayne Fong",
      basketballWinPer: 0.565,
      baseballWinPer: 0.75,
      footballWinPer: 0.25,
      totalWinPer: 0.522,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      basketballWinPer: 0.444,
      baseballWinPer: 0.403,
      footballWinPer: 0.6,
      totalWinPer: 0.482,
    },
    {
      ownerNames: "Marcus Lam",
      basketballWinPer: 0.435,
      baseballWinPer: 0.635,
      footballWinPer: 0.333,
      totalWinPer: 0.468,
    },
    {
      ownerNames: "Bryan Kuh",
      basketballWinPer: 0.37,
      baseballWinPer: 0.661,
      footballWinPer: 0.333,
      totalWinPer: 0.455,
    },
    {
      ownerNames: "Tim Fong",
      basketballWinPer: 0.444,
      baseballWinPer: 0.464,
      footballWinPer: 0.4,
      totalWinPer: 0.436,
    },
    {
      ownerNames: "Nick Wang",
      basketballWinPer: 0.407,
      baseballWinPer: 0.593,
      footballWinPer: 0.25,
      totalWinPer: 0.417,
    },
    {
      ownerNames: "Joshua Aguirre",
      basketballWinPer: 0.463,
      baseballWinPer: 0.59,
      footballWinPer: 0,
      totalWinPer: 0.351,
    },
    {
      ownerNames: "Joshua Apostol",
      basketballWinPer: 0.463,
      baseballWinPer: 0.443,
      footballWinPer: 0.0,
      totalWinPer: 0.302,
    },
  ],
  basketballMatchups: [
    {
      ownerNames: "Wayne Fong",
      wins: 30,
      losses: 23,
      ties: 1,
      winPer: 0.565,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 25,
      losses: 29,
      ties: 0,
      winPer: 0.463,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 24,
      losses: 28,
      ties: 2,
      winPer: 0.463,
    },
    {
      ownerNames: "Tim Fong",
      wins: 24,
      losses: 30,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 24,
      losses: 30,
      ties: 0,
      winPer: 0.444,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 23,
      losses: 30,
      ties: 1,
      winPer: 0.435,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 22,
      losses: 30,
      ties: 2,
      winPer: 0.426,
    },
    {
      ownerNames: "Nick Wang",
      wins: 21,
      losses: 31,
      ties: 2,
      winPer: 0.407,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 19,
      losses: 33,
      ties: 2,
      winPer: 0.37,
    },
  ],
  baseballMatchups: [
    {
      ownerNames: "Wayne Fong",
      wins: 69,
      losses: 21,
      ties: 6,
      winPer: 0.75,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 59,
      losses: 28,
      ties: 9,
      winPer: 0.661,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 58,
      losses: 32,
      ties: 6,
      winPer: 0.635,
    },
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 41,
      losses: 24,
      ties: 7,
      winPer: 0.618,
    },
    {
      ownerNames: "Nick Wang",
      wins: 61,
      losses: 41,
      ties: 6,
      winPer: 0.593,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 41,
      losses: 28,
      ties: 3,
      winPer: 0.59,
    },
    {
      ownerNames: "Tim Fong",
      wins: 36,
      losses: 42,
      ties: 6,
      winPer: 0.464,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 39,
      losses: 50,
      ties: 7,
      winPer: 0.443,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 27,
      losses: 41,
      ties: 4,
      winPer: 0.403,
    },
  ],
  footballMatchups: [
    {
      ownerNames: "Ryan Tomimitsu",
      wins: 4,
      losses: 2,
      ties: 0,
      winPer: 0.667,
      pointsFor: 604.9,
      pointsAgainst: 596.5,
      pointsDiff: 8.4,
    },
    {
      ownerNames: "Kevin Okamoto, Joshua Liu",
      wins: 3,
      losses: 2,
      ties: 0,
      winPer: 0.6,
      pointsFor: 492.5,
      pointsAgainst: 483.3,
      pointsDiff: 9.2,
    },
    {
      ownerNames: "Tim Fong",
      wins: 2,
      losses: 3,
      ties: 0,
      winPer: 0.4,
      pointsFor: 481.9,
      pointsAgainst: 534.3,
      pointsDiff: -52.4,
    },
    {
      ownerNames: "Marcus Lam",
      wins: 2,
      losses: 4,
      ties: 0,
      winPer: 0.333,
      pointsFor: 580.7,
      pointsAgainst: 630.4,
      pointsDiff: -49.7,
    },
    {
      ownerNames: "Bryan Kuh",
      wins: 1,
      losses: 2,
      ties: 0,
      winPer: 0.333,
      pointsFor: 266.3,
      pointsAgainst: 317.7,
      pointsDiff: -51.4,
    },
    {
      ownerNames: "Nick Wang",
      wins: 1,
      losses: 3,
      ties: 0,
      winPer: 0.25,
      pointsFor: 331,
      pointsAgainst: 348.8,
      pointsDiff: -17.8,
    },
    {
      ownerNames: "Wayne Fong",
      wins: 1,
      losses: 3,
      ties: 0,
      winPer: 0.25,
      pointsFor: 387.4,
      pointsAgainst: 408.4,
      pointsDiff: -21,
    },
    {
      ownerNames: "Joshua Aguirre",
      wins: 0,
      losses: 3,
      ties: 0,
      winPer: 0,
      pointsFor: 241.6,
      pointsAgainst: 282.9,
      pointsDiff: -41.3,
    },
    {
      ownerNames: "Joshua Apostol",
      wins: 0,
      losses: 3,
      ties: 0,
      winPer: 0,
      pointsFor: 238.9,
      pointsAgainst: 345.2,
      pointsDiff: -106.3,
    },
  ],
};
