export const SAVE_CALCULATED_TRIFECTA_STANDINGS =
  "SAVE_CALCULATED_TRIFECTA_STANDINGS";
export const SAVE_EXISTING_TRIFECTA_STANDINGS =
  "SAVE_EXISTING_TRIFECTA_STANDINGS";
export const SET_TRIFECTA_STANDINGS_LAST_SCRAPED =
  "SET_TRIFECTA_STANDINGS_LAST_SCRAPED";
export const SORT_TRIFECTA_STANDINGS_TABLE = "SORT_TRIFECTA_STANDINGS_TABLE";
